### ISSUE TITLE
Pytorch and AMD GPU

### ISSUE THREAD

**Issue by Flock1** [RadeonOpenCompute/ROCm#1570]
Hi,

I am using RX 6700 on my Ubuntu machine and have installed ROCm as well. When I install Pytorch for ROCma nd import it, I get the following:
```
"hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"
Aborted (core dumped)
```
Why am I getting this?

**Comment by aoolmay** [comment]
There is no support yet, there's a lot of promises with ever further timeline for it though.

What you can do in the meantime is use PlaidML over OpenCL provided by ROCm. It's using old Keras which is not great and lacking features, but it might get you by for a while.

**Comment by Flock1** [comment]
Hi,

Thanks for the reply. I tried PlaidML but when I enter the setup, I only see my CPU. The GPU isn't showing up

**Comment by aoolmay** [comment]
It only shows up if you accept 'experimental device support' prompt.
If it doesn't show, check you clinfo and rocminfo, something might go wrong on ROCm install.

**Comment by Flock1** [comment]
When I run `clinfo`, I get `gfx1031` as the name of the device. I din't get any error when I run `clinfo` or `rocminfo`

**Comment by aoolmay** [comment]
You must've missed the experimental device support prompt, it defaults to no and because of that didn't show OpenCL enabled GPU.

**Comment by Flock1** [comment]
No. it didn't show up. Only the CPU showed up.

**Comment by aoolmay** [comment]
Maybe it's something to do with current ROCm version? I'm still on 4.2 and it works on different machines with different AMD GPUs with no problems.

**Comment by Flock1** [comment]
I am using 4.3

**Comment by aoolmay** [comment]
Now that i think about i might have the 4.3 installed on one of machines and gave me some problems with Plaid.
You can do that by changing default repository in "software&updates->other software" to "https://repo.radeon.com/rocm/apt/4.2/". Remember to uninstall 4.3 version first.

**Comment by Flock1** [comment]
So [here](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#ubuntu), how do I ensure I install 4.2 instead of 4.3?

**Comment by aoolmay** [comment]
Ok, step by step.
1. Uninstall 4.3 with "sudo apt autoremove rocm-opencl rocm-dkms rocm-dev rocm-utils && sudo reboot"
2. After the reboot you have to go into "software&updates" system application, in the tab "other software" you will find the default address for rocm repository "https://repo.radeon.com/rocm/apt/debian/", change it to "https://repo.radeon.com/rocm/apt/4.2/"
3. Update your package manager with new repository with "sudo apt update"
4. Install ROCm version 4.2 with "sudo apt install rocm-dkms && sudo reboot"
5. If version 4.2 works properly you will find your GPU in the plaid-setup.

**Comment by Flock1** [comment]
Thank you very much. Let me try that.

**Comment by Flock1** [comment]
I'm not able to install 4.2. Getting this error:
```
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by aoolmay** [comment]
Sorry about leading you to a problem. Try "sudo dpkg --configure -a", if this won't work i'd just reinstall Ubuntu, it takes just as much time as troubleshooting.

**Comment by Flock1** [comment]
Also, after `sudo apt update` in step 3, I get the following:
`N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://repo.radeon.com/rocm/apt/4.2 ubuntu InRelease' doesn't support architecture 'i386'
`

**Comment by aoolmay** [comment]
These are fine, it's just warnings with no consequence.

**Comment by Flock1** [comment]
Step 4 gives me this:
```
Errors were encountered while processing:
 rock-dkms
 rocm-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by aoolmay** [comment]
Did you change repository path before, when i first sugested installing 4.2?

**Comment by Flock1** [comment]
No. When you provided me with the steps, that's when I changed it

**Comment by aoolmay** [comment]
Then again, it's a package manager problem and time consuming to diagnose and fix, epsecially if you're not familiar with Ubuntu. Can you afford time to just reinstall Ubuntu?

**Comment by Flock1** [comment]
Yeah. I can reinstall it. But what's the solution though? Can you give me some idea? I have worked with Ubuntu for some time now.

**Comment by aoolmay** [comment]
Yes, follow standard installation procedure https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#ubuntu
After step 2 "Add the ROCm apt repository" change default address for rocm repository "https://repo.radeon.com/rocm/apt/debian/" to "https://repo.radeon.com/rocm/apt/4.2/".
Proceed with installation as normal.
Install PlaidML and you should see your GPU in the list.

**Comment by Flock1** [comment]
is 4.2 compatible with RX 6700? I want to be sure before I reinstall the OS

**Comment by aoolmay** [comment]
I'm using ROCm 4.2 with PlaidML on machines with WX5100, WX7100 and RX6800. Make sure to use the officially supported kernel version, i vaguely remember that caused some problems.

**Comment by Flock1** [comment]
Ah. Let me reinstall the OS then.

**Comment by Flock1** [comment]
So now that I'm doing a fresh installation, how do I proceed? I don't see the option in "software and updates"

**Comment by aoolmay** [comment]
I'm using Xubuntu, i don't exactly know what your flavor of Ubuntu allows, quick search suggest you may have a thing called "software updater" in the vanilla?
![2021-09-10_22-07](https://user-images.githubusercontent.com/87392079/132911586-75053559-3f50-4cd3-bf2f-52f66077d1ba.png)

**Comment by Flock1** [comment]
So here's what I did:
1) Installed new OS
2) Followed the initial steps on the website
3) Instead of using the mentioned key, I got the key for 4.2
4) Then, I opened the software and update and I changed the link as you mentioned. 
5) Then, I installed using the apt command to install rocm. 

I still got the error.

**Comment by aoolmay** [comment]
https://github.com/RadeonOpenCompute/ROCm/tree/roc-4.2.x#Supported-Operating-Systems
Kernel and Ubuntu version is correct?
I'm puzzled, this solution works for me and i reinstalled one of the system just two weeks ago.

**Comment by Flock1** [comment]
It installs fine when I install 4.3. Something is wrong with 4.2

**Comment by aoolmay** [comment]
I'm not aware if there were any changes to 4.2. I remember using PlaidML with 4.0 before, you could try 4.0 or 4.1.

**Comment by Flock1** [comment]
Let's see

**Comment by Flock1** [comment]
I am following this to install the ROCm. This works for me
https://www.youtube.com/watch?v=efKjfBkjPlM

**Comment by aoolmay** [comment]
This guy shows steps you should be doing from ROCm installation manual and this is always for current version, which now is 4.3.
The problem you're having is that 4.3 doesn't work with PlaidML and 4.2 and earlier do. You have to figure out how to succesfully install 4.2 or earlier.
For me simply changing the repository directory always worked. I can't help you further, out of time.

**Comment by Flock1** [comment]
So in the above video, can you tell me what should I use version 4.2 so that it installs?

**Comment by briansp2020** [comment]
You can follow the installation guide at https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html

To pick a specific version, instead of 
>echo 'deb [arch=amd64] https://repo.radeon.com/rocm/apt/debian/ ubuntu main' | sudo tee /etc/apt/sources.list.d/rocm.list
Use specific version you want
>echo 'deb [arch=amd64] https://repo.radeon.com/rocm/apt/4.2/ ubuntu main' | sudo tee /etc/apt/sources.list.d/rocm.list

Other than that, all the instructions should be the same. I don't have Ubuntu on my PC any more. So, I can't try it to verify it myself.

**Comment by Flock1** [comment]
I tried that. I get this error

> Step 4 gives me this:
> 
> ```
> Errors were encountered while processing:
>  rock-dkms
>  rocm-dkms
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> ```

**Comment by Flock1** [comment]
So guys, an update. I did fresh installation and I was bale to set AMD GPU in plaid setup.

**Comment by Flock1** [comment]
When I ran `plaidbench keras mobilenet`, I got this:
```
plaidbench keras mobilenet
Running 1024 examples with mobilenet, batch size 1, on backend plaid
INFO:plaidml:Opening device "opencl_amd_gfx1031.0"
Compiling network... Warming up... Running...
Example finished, elapsed: 5.100s (compile), 2.723s (execution)

-----------------------------------------------------------------------------------------
Network Name         Inference Latency         Time / FPS          
-----------------------------------------------------------------------------------------
mobilenet            2.66 ms                   1.21 ms / 829.15 fps
Correctness: PASS, max_error: 7.314303729799576e-06, max_abs_error: 6.407499313354492e-07, fail_ratio: 0.0
```
So is my GPU working?

**Comment by aoolmay** [comment]
Yes, good job. Can you confirm which ROCm version works with PlaidML for you?

**Comment by Flock1** [comment]
I think I found a solution. I needed to set `LD_LIBRARY_PATH` variable to `/opt/rocm-<versoin>/bin`

**Comment by ROCmSupport** [comment]
Hi @Flock1 
Thanks for reaching out.
RX 6700 is not an officially supported card. Please look at supported hardware section @ [https://github.com/RadeonOpenCompute/ROCm#hardware-and-software-support](url)
Thank you.
