### ISSUE TITLE
Support for Vega 56/64 [ROCm 4.3 / Pytorch]

### ISSUE THREAD

**Issue by s-marios** [RadeonOpenCompute/ROCm#1572]
Hi,

So, first things first, are Vega 56 GPUs supported?

I'm running pytorch on an lxc container. With a Radeon VII it works fine. But with a Vega 56 I'm getting the following error:
```
(snip)

MIOpen(HIP): Error [SetIsaName] 'amd_comgr_action_info_set_isa_name(handle, isa.c_str())' amdgcn-amd-amdhsa--gfx900:sramecc-:xnack-: INVALID_ARGUMENT (2)
MIOpen(HIP): Error [BuildOcl] comgr status = INVALID_ARGUMENT (2)
MIOpen(HIP): Warning [BuildOcl] amdgcn-amd-amdhsa--gfx900:sramecc-:xnack-
MIOpen Error: /MIOpen/src/hipoc/hipoc_program.cpp:286: Code object build failed. Source: MIOpenIm2d2Col.cl
Traceback (most recent call last):
  File "train2.py", line 100, in <module>
    train(model, optimizer, train_loader, reps_per_epoch, device)
  File "train2.py", line 60, in train
    loss_dict = model(inputs, targets)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/detection/generalized_rcnn.py", line 93, in forward
    features = self.backbone(images.tensors)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/detection/backbone_utils.py", line 44, in forward
    x = self.body(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/_utils.py", line 62, in forward
    x = module(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 443, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 439, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: miopenStatusUnknownError
```

I've noticed that rocminfo reports `amdgcn-amd-amdhsa--gfx900:xnack-` wheras the above HIP stuff uses `amdgcn-amd-amdhsa--gfx900:sramecc-:xnack-` i.e. `sramecc` doesn't seem to be supported.

I have access to both a Radeon VII/threadripper 3990 and Vega 56/threadripper 2990wx systems and can provide comparisons between them.

Please advise!

**Comment by ROCmSupport** [comment]
Thanks @s-marios for reaching out.
I will check this for you and get back with an update soon.
Meanwhile can you please share the exact steps to reproduce the problem.
Thank you.

**Comment by s-marios** [comment]
I will report detailed steps tomorrow (work day is over), but the gist is this:
0) Using kernel >=5.13 (currently 5.14)
1) setup an Ubuntu:20.04 lxc container (my setup: lxd/snap/debian)
2) pass in /dev/kfd (as unix-char) and /dev/dri (as gpu)
3) add rocm repositories and install rocm-dev only
4) install pytorch using pip
5) run some pytorch code 

Let me know for which steps you need more details and I'll come back to it tomorrow. Again, do note that the Radeon VII setup works fine.

**Comment by s-marios** [comment]
Ok, I'm back with a more detailed writeup and sample code for you.

In [setup.txt](https://github.com/RadeonOpenCompute/ROCm/files/7174165/setup.txt) you'll find all the steps I followed to build a (new) LXC container, with the same error results. This can be used as a guide to build an LXC ROCm container.

Below you'll find a minimal example that triggers the problem (I can't attach .py files directly, so I'm pasting it as-is).

```
import torch
import torchvision

device = torch.device("cuda" if torch.cuda.is_available() else 'cpu')
print(f"using device: {device}")
model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True).to(device)
model.eval()

rand_input = torch.rand(3, 1920, 1080, device=device)
model([rand_input])
```

Looking forward to your thoughts on this.
Cheers,

**Comment by ROCmSupport** [comment]
Thanks @s-marios 
I am able to reproduce the problem with Vega64.
From the logs its pointing to MIOpen and so looks like its MIOpen issue. Let me assign to MIOpen team to take a look.
Thank you.

**Comment by s-marios** [comment]
> Thanks @s-marios
> I am able to reproduce the problem with Vega64.
> From the logs its pointing to MIOpen and so looks like its MIOpen issue. Let me assign to MIOpen team to take a look.
> Thank you.

Right on! Hoping for a quick resolution, possibly in a point release. Please don't make me wait until ROCm 4.5, pretty please? 

Cheers!

**Comment by ROCmSupport** [comment]
Hi @s-marios 
I am not sure about the availability of fix right now, developer is working on it.
Once I hear from him, I will update you.
Thank you.

**Comment by Sigura** [comment]
> From the logs its pointing to MIOpen and so looks like its MIOpen issue. Let me assign to MIOpen team to take a look.

Hi @ROCmSupport 

I got the same issue on Vega64, trying to rebuild MIOpen from the source without any result. Could you please share the MIOpen issue number?

**Comment by Bengt** [comment]
Yes, me too. Using 4.2 is possible, but it seems to not fix the issue.

**Comment by jeffdaily** [comment]
FYI nightly wheel was updated since I last commented.  Should resolve the miopen issue.  Let us know otherwise.

**Comment by Bengt** [comment]
@jeffdaily Thanks for the update. I upgraded the `torch` and `torchvision` packages, like so:

```
.tox/py38/bin/python -m pip uninstall --yes torch torchvision
.tox/py38/bin/python -m pip install torch torchvision -f https://download.pytorch.org/whl/nightly/rocm4.3.1/torch_nightly.html
```

I have a test that checks for GPU acceleration in torch, like so:

```Python
import socket
from typing import Tuple

from torch import cuda as cuda_or_rocm  # ROCm identifies as CUDA, too.


def test_cuda_rocm_availability():
    # Mock
    hostnames_with_gpus: Tuple[str] = tuple([
        'bengt-desktop',
        'dgx-ol-1',
    ])
    hostname: str = socket.gethostname()
    expected_availability = hostname in hostnames_with_gpus

    # Test
    actual_availability: bool = cuda_or_rocm.is_available()

    # This might fail on weird machines in the future.
    # So print quite verbosely for debugging purposes.
    print(f'[DEBUG] Hostname: {hostname}')
    print(f'[DEBUG] Hostnames with GPUs: {hostnames_with_gpus}')
    print(f'[DEBUG] Hostname in hostnames with GPUs: {expected_availability}')
    print(f'[DEBUG] CUDA availability: {actual_availability}')

    # Assert
    assert actual_availability or \
        actual_availability == expected_availability
```

This test now fails, like so:

```
FAILED            [100%][DEBUG] Hostname: bengt-desktop
[DEBUG] Hostnames with GPUs: ('bengt-desktop', 'dgx-ol-1')
[DEBUG] Hostname in hostnames with GPUs: True
[DEBUG] CUDA availability: False

pytorch/test_cuda_rocm.py:6 (test_cuda_rocm_availability)
(False or False != True)

Expected :True)
Actual   :(False or False
<Click to see difference>

def test_cuda_rocm_availability():
        # Mock
        hostnames_with_gpus: Tuple[str] = tuple([
            'bengt-desktop',
            'dgx-ol-1',
        ])
        hostname: str = socket.gethostname()
        expected_availability = hostname in hostnames_with_gpus
    
        # Test
        actual_availability: bool = cuda_or_rocm.is_available()
    
        # This might fail on weird machines in the future.
        # So print quite verbosely for debugging purposes.
        print(f'[DEBUG] Hostname: {hostname}')
        print(f'[DEBUG] Hostnames with GPUs: {hostnames_with_gpus}')
        print(f'[DEBUG] Hostname in hostnames with GPUs: {expected_availability}')
        print(f'[DEBUG] CUDA availability: {actual_availability}')
    
        # Assert
>       assert actual_availability or \
            actual_availability == expected_availability
E       assert (False or False == True)

pytorch/test_cuda_rocm.py:27: AssertionError
```

I also recreated the virtual environment from scratch using tox, but that did not help.

This is on Ubuntu 20.04.1, ROCm 4.5.0 and a Vega 64 (gfx900).

**Comment by Bengt** [comment]
I noticed that `rocminfo` and `clinfo` still disagree about device naming:

```
$ clinfo | grep gfx900
  Device Name                                     gfx900:xnack-
    Device Name                                   gfx900:xnack-
    Device Name                                   gfx900:xnack-
    Device Name                                   gfx900:xnack-
```

```
$ rocminfo | grep gfx900
  Name:                    gfx900                             
      Name:                    amdgcn-amd-amdhsa--gfx900:xnack-   
```

**Comment by jeffdaily** [comment]
> ```
> .tox/py38/bin/python -m pip install torch torchvision -f https://download.pytorch.org/whl/nightly/rocm4.3.1/torch_nightly.html
> ```

Did you miss the `--pre` option?  It is needed for nightly wheels or you don't get the prerelease version.

**Comment by Bengt** [comment]
I am trying this now:

```
.tox/py38/bin/python -m pip uninstall --yes torch torchvision
.tox/py38/bin/python -m pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/rocm4.3.1/torch_nightly.html
```

**Comment by Bengt** [comment]
When can we expect the non-preview / stable package versions of `torch` and `torchvision` to work with the latest ROCm stack? A stable version should only require a minimal download and I would expected it on [the getting started page of pytorch.org](https://pytorch.org/get-started/locally/).

**Comment by jeffdaily** [comment]
Admittedly, our pytorch wheel availability is deficient.  We missed the cutoff for pytorch 1.10 branching before we got rocm 4.3.1 wheel support added.  During the pytorch 1.10 release process, we released rocm 4.5.  So now the getting started page remains at 4.2, confusingly, even though we are now up to rocm 4.5.  We plan a patch release of rocm 4.5.1 that should be out prior to the next pytorch branching (1.11), but we don't expect a new pytorch until Q1'22.  

A stable version would be a similar size compared to the nightly wheels.

**Comment by s-marios** [comment]
Updated to the new nightly wheel using `--pre`, and the sample code finishes without problems! Closing this ticket as fixed.

Just a clarification, are these fixes present in ROCm 4.5?

**Comment by ROCmSupport** [comment]
Hi @s-marios  and all,
Good news is that fix is ready from MIOpen and planning to push into upcoming release.
Please stay tuned for more updates.
Thank you.

**Comment by Bengt** [comment]
@jeffdaily I understand that releasing with that many dependencies is difficult. What are the next steps under these circumstances? Should the nightly builds of `torch` and `torchvision` move to building against ROCm 4.5.0 instead of ROCm 4.3.1?

I managed to caching speed up building my code in CI by caching the environment into which the ROCm versions of PyTorch and TorchVision get installed. This may not work for anyone, though. Is there a way to provide smaller packages, which are thus quicker to install for everybody?

**Comment by jeffdaily** [comment]
> just a clarification, are these fixes present in ROCm 4.5?

@s-marios We expect these fixes to be part of ROCm 4.5.1, not 4.5.0. 

> I understand that releasing with that many dependencies is difficult. What are the next steps under these circumstances? Should the nightly builds of torch and torchvision move to building against ROCm 4.5.0 instead of ROCm 4.3.1?

@Bengt we are skipping 4.5 in favor of 4.5.1 when we upgrade the nightly builds of torch and torchvision.  ETA mid December.  Our release cadence is approximately every other month, with patch releases as-needed.  Upgrading CI, wheels, etc. is not trivial, and combined with the aggressive release schedule we try to minimize the churn.  

Concerning the size of the rocm pytorch wheels, we are following the precedent established by the cuda pytorch wheels where the toolkit libraries are bundled into the wheel.  That means if you have rocm 4.5.0 installed on your host and you pip install the rocm 4.3.1 wheel, you get rocm 4.3.1 libs inside the wheel.  We strive to maintain "N-2" backwards compatibility with the rocm kernel driver, so this use case is expected.

**Comment by ROCmSupport** [comment]
Good news. I verified and this issue is fixed and no more observed with 4.5.2.
Thank you.

**Comment by Bengt** [comment]
There is a tag, but no release, yet:

https://github.com/RadeonOpenCompute/ROCm/tags

https://github.com/RadeonOpenCompute/ROCm/releases

**Comment by zhang2amd** [comment]
ROCm releases are labeled as tags. We may add "Releases" but that's optional. There is no real difference between Tag and Release on github. This ROCm repository does not have binaries. The release notes and all docs are updated on the tags. And there is no good way to automate adding "Release". Please just look for Tags as they are labeled for each releases. We may manually add "Releases" based on the tags or do it later or skip it. Just to answer this question, we added 4.5.2 Release.

**Comment by Bengt** [comment]
@zhang2amd cool! Thanks for adding the release. I feel better with that one in place. This makes it clear that 4.5 is no longer the most recent version. So hopefully some more people using Vega 64 cards can avoid this faulty version.
