### ISSUE TITLE
"hipErrorNoBinaryForGpu" for rx 6700 xt (Navi 22)

### ISSUE THREAD

**Issue by kvirikroma** [RadeonOpenCompute/ROCm#1668]
AFAIK, Navi 21 is supported by ROCm, and some users even were able to replace some values in source code to make a software think that Navi 22 is actually supported (and assuming they don't lie, it really works for them), but for some reason, there's no official support for rx 6700 xt yet. It would be really nice if you let me know if such support is planned. Thanks (=

**Comment by aoolmay** [comment]
Some did report Navi working, i only got 6800xt/6900xt machines to work using the docker provided in installation manual. No bare metal experience. If you can afford the docker compromise, you should give it a try.

**Comment by kvirikroma** [comment]
@aoolmay Thanks for the advice.
I've tried docker already, but basically what I did to make it work is added host devices (/dev/dri and /dev/kfd) to the container and it worked for my old rx570 (with older versions of rocm). So I think it is the same as doing it on bare metal. At least an error for rx6700xt is the same with docker and without it (hipErrorNoBinaryForGpu).

**Comment by kvirikroma** [comment]
@xuhuisheng Thank you for the advice, that sounds promising. I'll probably try it in a few days, but I don't know much about compiling ROCm. I have a lot of packages related to it installed in my system now, do I need to compile each of them separately? And where it would be correct to get sources from? I know about https://github.com/ROCmSoftwarePlatform/ but I'm not sure that I'm on the right way. Could you please send me some guide or documentation on compiling ROCm from the source?

**Comment by xuhuisheng** [comment]
@kvirikroma
Here is my building script. <https://github.com/xuhuisheng/rocm-build>

**Comment by kvirikroma** [comment]
@xuhuisheng thank you (=

**Comment by aoolmay** [comment]
@kvirikroma @xuhuisheng  I've just spotted fresh tensorflow-rocm package, version 2.8.0, in pip. Works on bare metal with 6800xt, installed the driver with "rocm,hip,opencl" and simple pip install tensorflow-rocm. I've yet to test 6900xt, don't have other NAVI cards, i hope it works for you on 6700xt.

**Comment by ROCmSupport** [comment]
Hi @kvirikroma 
Thanks for reaching out.
ROCm does not support Navi22 and so can not comment on this.
For supported hardware, please check [https://docs.amd.com/bundle/ROCm_Release_Notes_v5.0/page/About_This_Document.html](url)
Thank you.

**Comment by NJannasch** [comment]
For the 6700xt this link might be interesting:
https://www.zhihu.com/question/469674526/answer/2189926640
->
https://www-zhihu-com.translate.goog/question/469674526/answer/2189926640?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=de&_x_tr_pto=wapp

**Comment by kvirikroma** [comment]
#https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1528

**Comment by arcaspo** [comment]
@xuhuisheng Will your build script, https://github.com/xuhuisheng/rocm-build, work for Navi 23? I only see up to navi 21, so if i change AMDGPU_TARGETS to gfx1032 would the build work for the 6600xt?

**Comment by arcaspo** [comment]
Thanks, I’ll try later :)

**Comment by julianoes** [comment]
One more thing to check, make sure the user is in the `video` and `render` group.

```
sudo usermod -a -G video $LOGNAME
sudo usermod -a -G render $LOGNAME
```

Then logout and log back in, and check whether the groups are listed when running `groups`. In my case a reboot was required.

**Comment by SamuelMarks** [comment]
@xuhuisheng Open to testing with my Navi 22 [AMD Radeon(TM) RX 6850M XT 12GB GDDR6] on Linux kernel 6.2.8 running Ubuntu 22.10 (soon 23.04?). Going through your repo now.

(any tips from anyone here is most welcome)
