### ISSUE TITLE
ROCm 5.0 don't  work with Pytorch

### ISSUE THREAD

**Issue by EduMio** [RadeonOpenCompute/ROCm#1684]
Good afternoon to everyone,
I have a problem where ROCm 5.0.0 don't work with Pytorch. I downloaded the docker container "rocm/pytorch:latest" and I am trying to run the tests with the command "./.jenkins/pytorch/test.sh", which tells me that "RuntimeError: HIP error: hipErrorLaunchFailure". I tried launching the tests again with "HIP_LAUNCH_BLOCKING=1 ./.jenkins/pytorch/test.sh" with the same results. I am using Ubuntu 20.04 and a Radeon RX 6900xt, and I downloaded my ROCm version with the "amdgpu-install --usecase=hip,hiplibsdk,rocm,graphics,opencl".

**Comment by EduMio** [comment]
Well, turns out pytorch is not yet functional with ROCm 5.0.0, ROCm 4.5.2 works just fine.

**Comment by ROCmSupport** [comment]
Hi @EduMio 
Pytorch should work with ROCm 5.0, am not sure how come its not working.
Please share more details for better understanding.

**Comment by EduMio** [comment]
> Hi @EduMio Pytorch should work with ROCm 5.0, am not sure how come its not working. Please share more details for better understanding.

Well that is surprising, because in the [documentation](https://docs.amd.com/bundle/AMD-Deep-Learning-Guide-v5.0/page/Prerequisites.html) it states that the ROCm 5.0 is still not compatible with any version of pytorch. 
Anyway, it is possible that I make a mistake in the installation, I can not provide more information about the situation because I already uninstalled ROCm 5.0 and installed the 4.5.2 version, which is working for me.

**Comment by ROCmSupport** [comment]
Not sure where you are pointing about 5.0+pytorch
Anyhow looks like you are happy with 4.5 for now. Thanks then.
I am closing this issue.

**Comment by ROCmSupport** [comment]
I am reopening this issue and working with Documentation team on fixing the docker image name.
Will keep posted.

**Comment by ROCmSupport** [comment]
Hi @EduMio 
Documentation team is working on modifications.
Meanwhile I request to try with below docker.

rocm/pytorch:rocm5.0_ubuntu18.04_py3.7_pytorch_staging --> has Navi21 enabled

Thank you.

**Comment by EduMio** [comment]
I just tested it and it works perfectly. Thank you very much!

> Hi @EduMio Documentation team is working on modifications. Meanwhile I request to try with below docker.
> 
> rocm/pytorch:rocm5.0_ubuntu18.04_py3.7_pytorch_staging --> has Navi21 enabled
> 
> Thank you.

**Comment by ROCmSupport** [comment]
Hi All,
rocm/pytorch:latest has Navi21 enabled and so recommend to try the same. Documentation is also updated with the same information.
Thank you.
