### ISSUE TITLE
How to allocate more memory to my Ryzen APU's GPU?

### ISSUE THREAD

**Issue by winstonma** [RadeonOpenCompute/ROCm#2014]
I am running AMD 6800U on my Ubuntu 22.04 and I installed the AMD driver. I checked that the default system would allocate 512MB RAM to VRAM to the GPU.

I followed [some instruction](https://github.com/RadeonOpenCompute/ROCm/issues/1756#issuecomment-1159603527) from other github issue to create a rocm/pytorch docker image and it has no problem detecting my GPU but it has problem running sample program, due to `OutOfMemoryError`.

```
torch.cuda.OutOfMemoryError: HIP out of memory. Tried to allocate 2.00 MiB (GPU 0; 512.00 MiB total capacity; 150.39 MiB already allocated; 312.00 MiB free; 168.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_HIP_ALLOC_CONF
```

So my guess is ROCm support APU but I just need to allocate more system memory to my GPU before going into the docker environment. Are there any people who know how to modify the memory allocation of AMD APU? Thanks in advance

**Comment by ye-luo** [comment]
An alternative route is to change the DMC buffer to 2GB in your BIOS.

**Comment by winstonma** [comment]
Thanks

I tried to find that but it doesn't exist. Also it seems to me that [AMD APU memory setting are now on driver level ](https://community.amd.com/t5/graphics/increase-vram/m-p/538890)

**Comment by Ristovski** [comment]
It appears ROCm does not take into account dynamic VRAM GTT allocation on APUs (handled by amdkfd?).

For example on my system:
```
[    3.524465] [drm] amdgpu: 64M of VRAM memory ready
[    3.524466] [drm] amdgpu: 15916M of GTT memory ready.
```

This means the iGPU could allocate up to 16GB of VRAM, however due to the small dedicated VRAM (64MB) that is _reserved_ for the iGPU, ROCm processes fail to allocate memory.

This also seems to propagate to OpenCL:
```
$ clinfo |grep -i memory
  Global memory size                              67108864 (64MiB)
  Global free memory (AMD)                        65536 (64MiB) 65536 (64MiB)
  Global memory channels (AMD)                    4
  Global memory banks per channel (AMD)           4
  Global memory bank width (AMD)                  256 bytes
  Max memory allocation                           57042528 (54.4MiB)
  Unified memory for Host and Device              No
  Shared Virtual Memory (SVM) capabilities        (core)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        16384 (16KiB)
  Global Memory cache line size                   64 bytes
  Local memory type                               Local
  Local memory size                               65536 (64KiB)
  Local memory size per CU (AMD)                  65536 (64KiB)
  Local memory banks (AMD)                        32
```

This is NOT the case for OpenGL tho (snippet of `glxinfo -B`):
```
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 206 MB, largest block: 206 MB
    VBO free aux. memory - total: 15138 MB, largest block: 15138 MB
    Texture free memory - total: 206 MB, largest block: 206 MB
    Texture free aux. memory - total: 15138 MB, largest block: 15138 MB
    Renderbuffer free memory - total: 206 MB, largest block: 206 MB
    Renderbuffer free aux. memory - total: 15138 MB, largest block: 15138 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 256 MB
    Total available memory: 16172 MB
```

**Comment by winstonma** [comment]
@Ristovski Thanks for the answer

I think this is a needed feature (otherwise all the APU would be ROCm-compatible but it doesn't work due to the memory allocation problem).

I am not sure if this should be fixed on the driver level or the ROCm level (or both).

**Comment by asbachb** [comment]
This bug is indeed super annoying. Most laptop models only provide limited settings regarding UMA buffer size. So ROCm is quite limited or useless for APUs on Linux.

**Comment by winstonma** [comment]
Thanks @asbachb I plan to just use my laptop just to do some primitive testing with a subset of data. I didn't plan to some fancy calculation with all the data. But since I am using Ryzen CPU I think I could still get acceleration using the GPU with the subset.

**Comment by asbachb** [comment]
Just for reference some guy got some quite good results: (compared to CPU only): https://www.gabriel.urdhr.fr/2022/08/28/trying-to-run-stable-diffusion-on-amd-ryzen-5-5600g/

But he is able to set his VRAM to 16GB.

**Comment by winstonma** [comment]
May I share what I saw in Windows envoirnment?

My laptop has 16GB of memory. This is what is being shown inside task manager
![image](https://github.com/RadeonOpenCompute/ROCm/assets/1215090/fba8d680-fade-426c-b75b-dbd9c2f07c63)

It shows that the 
* Dedicated GPU memory is 512MB
* Shared GPU memory is 7.6GB
* GPU memory is 8.1GB (It should be 7.6GB+512MB)

While I play GTA it shows that I have 8GB of GPU memory. I would wonder if it is possible that the ROCm would have the similar fashion, "thinking" that my GPU has 8GB of GPU memory.

But when I reboot back to my Ubuntu it shows that my GPU has 512MB of memory, which I guess that's the dedicated GPU memory that you can view in Windows. However in the application perspective it sees 8GB of memory, to me it should be the same as ROCm application should be able to see that my system should have 8GB of GPU memory, similar to GTA result in Windows.

It seems to me there is a missing piece in between.

**Comment by winstonma** [comment]
@asbachb Sorry I forgot to answer the question in your post. First of all thank you very much.

I read the post and the author said that he modified the memory sharing behavior in BIOS. Which I don't have this settings in my laptop. Also in the previous answer the windows application sees the total GPU memory, not just the dedicated memory.

**Comment by randomstuff** [comment]
@winstonma, I'm the author of the "Stable diffusion on an AMD Ryzen 5 5600G" post. Sadly, I did not find any way to  increase the VRAM allocated to the iGPU without going to the BIOS/motherboard firmware.

**Comment by winstonma** [comment]
@randomstuff Thanks. But sadly the BIOS of my laptop doesn't have the VRAM allocation option. So I wonder if there are ways to increase the dedicated memory on system level (similar to [Regedit in Windows](https://www.lifewire.com/increase-vram-on-a-windows-pc-5072150))

**Comment by pomoke** [comment]
PyTorch  will work with replaced allocator which uses `hipHostMalloc`. I have a working snippet at <https://github.com/pomoke/torch-apu-helper>.

**Comment by winstonma** [comment]
For all who is interested in increasing dedicated memory in system, I wrote an article [Unlocking GPU Memory Allocation on AMD Ryzen™ APU](https://medium.com/p/e27b75905056) and thought that method I could adjust the amount of dedicated GPU memory, even the BIOS doesn't provide that option.

**Comment by winstonma** [comment]
> PyTorch will work with replaced allocator which uses `hipHostMalloc`. I have a working snippet at https://github.com/pomoke/torch-apu-helper.

Thanks.

I currently using alternative ways to unlock the BIOS, modify the amount of GPU dedicated memory to 8GB. After that I could run [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) using the [above method](https://github.com/RadeonOpenCompute/ROCm/issues/2014#issuecomment-1676583451) without any problem.

Also I cloned your repo, created `alloc.so` and add your code snippet in the launch.py of [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/launch.py). When I start running stable diffusion then it starts with a warning (but it can start):

```
Warning: caught exception 'CUDAPluggableAllocator does not yet support getDeviceStats. If you need it, please file an issue describing your use case.', memory monitor disabled
```

However when I start generating image I got the following error:

```
RuntimeError: CUDAPluggableAllocator does not yet support getDeviceStats. If you need it, please file an issue describing your use case.
```

And no image is being generated. I am not sure if I miss anything. @pomoke not sure if you feel free to try running stable-diffusion-webui on your APU. Thanks

**Comment by winstonma** [comment]
In conclusion, there are several solutions for other AMD APU user

- [Override the BIOS settings to allocate more memory](https://github.com/RadeonOpenCompute/ROCm/issues/2014#issuecomment-1676583451). This method like the old days that you set your dedicated video memory in BIOS. More VRAM means less system memory.
- [torch-apu-helper](https://github.com/RadeonOpenCompute/ROCm/issues/2014#issuecomment-1653012878) uses the the Unified Memory Architecture (UMA), the APU would be able to allocate the memory from the system dynamically. It is a good demo but this way would not get all API working (e.g. getDeviceStats). If you are using application based on PyTorch, it would be likely that it would not work. I [filed an issue on PyTorch](https://github.com/pytorch/pytorch/issues/107605), hopefully they can add AMD APU support.

**Comment by pomoke** [comment]
Generally, we still need something like what we get on Tegra (Such as Jetson Developer Kit). CUDA on Tegra is capable of allocating GTT properly.

**Comment by winstonma** [comment]
Yes I think the problem now is the torch-apu-helper shows that PyTorch could grab system memory from the system as video memory. However I think it still need more PyTorch API porting so we can say this way is PyTorch ready. Not sure AMD or PyTorch would make this possible in the future.

**Comment by gwyllion92** [comment]
> Yes I think the problem now is the torch-apu-helper shows that PyTorch could grab system memory from the system as video memory. However I think it still need more PyTorch API porting so we can say this way is PyTorch ready. Not sure AMD or PyTorch would make this possible in the future.

Hi, I'm trying to follow your guide [https://winstonhyypia.medium.com/amd-apu-how-to-modify-the-dedicated-gpu-memory-e27b75905056](url) but when I run this command _SA_OVERRIDE_GFX_VERSION=10.3.0 python test-rocm.py_

I get this message: 
_Command "python" not found. Maybe your meant:
  "python3" command from the deb package "python3".
  the "python" command from the deb package "python-is-python3"._
  
  So I changed the command to _HSA_OVERRIDE_GFX_VERSION=10.3.0 python3 test-rocm.py_
  
 But I get this message now:
 _Traceback (most recent call last):
  File "/home/myUser/test-rocm.py", line 1, in <module>
    import torch, grp, pwd, os, subprocess
ModuleNotFoundError: No module named 'torch'_

I can't find any solution, and I'm not a programmer person.

**Thanks for your time!**

**Comment by winstonma** [comment]
> > Yes I think the problem now is the torch-apu-helper shows that PyTorch could grab system memory from the system as video memory. However I think it still need more PyTorch API porting so we can say this way is PyTorch ready. Not sure AMD or PyTorch would make this possible in the future.
> 
> Hi, I'm trying to follow your guide [https://winstonhyypia.medium.com/amd-apu-how-to-modify-the-dedicated-gpu-memory-e27b75905056](url) but when I run this command _SA_OVERRIDE_GFX_VERSION=10.3.0 python test-rocm.py_
> 
> I get this message: _Command "python" not found. Maybe your meant: "python3" command from the deb package "python3". the "python" command from the deb package "python-is-python3"._
> 
> So I changed the command to _HSA_OVERRIDE_GFX_VERSION=10.3.0 python3 test-rocm.py_
> 
> But I get this message now: _Traceback (most recent call last): File "/home/myUser/test-rocm.py", line 1, in import torch, grp, pwd, os, subprocess ModuleNotFoundError: No module named 'torch'_
> 
> I can't find any solution, and I'm not a programmer person.
> 
> **Thanks for your time!**

For PyTorch installation you need to check the PyTorch Official website. Here are the steps:

1. Go to [PyTorch Official Website](https://pytorch.org/get-started/locally/)
2. Scroll down a bit. You will see the widget like the one below
![image](https://github.com/ROCm/ROCm/assets/1215090/b34133a5-9574-49e8-aeca-c1efcb1b7dc3)
3. Just choose the option like the above image
4. You will get the command you need at the end. Then just copy and paste the command on your terminal.

**Comment by gwyllion92** [comment]
> > > Yes I think the problem now is the torch-apu-helper shows that PyTorch could grab system memory from the system as video memory. However I think it still need more PyTorch API porting so we can say this way is PyTorch ready. Not sure AMD or PyTorch would make this possible in the future.
> > 
> > 
> > Hi, I'm trying to follow your guide [https://winstonhyypia.medium.com/amd-apu-how-to-modify-the-dedicated-gpu-memory-e27b75905056](url) but when I run this command _SA_OVERRIDE_GFX_VERSION=10.3.0 python test-rocm.py_
> > I get this message: _Command "python" not found. Maybe your meant: "python3" command from the deb package "python3". the "python" command from the deb package "python-is-python3"._
> > So I changed the command to _HSA_OVERRIDE_GFX_VERSION=10.3.0 python3 test-rocm.py_
> > But I get this message now: _Traceback (most recent call last): File "/home/myUser/test-rocm.py", line 1, in import torch, grp, pwd, os, subprocess ModuleNotFoundError: No module named 'torch'_
> > I can't find any solution, and I'm not a programmer person.
> > **Thanks for your time!**
> 
> First of all, you need to make sure that you are
> 
>     1. Running Linux (I personally prefer Ubuntu LTS but any major linux release would do)
> 
>     2. You are running Ryzen APU, you can go to [AMD APU Website](https://www.amd.com/en/products/specifications/apu) and see if you can find your CPU
> 
> 
> For PyTorch installation you need to check the PyTorch Official website. Here are the steps:
> 
>     1. Go to [PyTorch Official Website](https://pytorch.org/get-started/locally/)
> 
>     2. Scroll down a bit. You will see the widget like the one below
>        ![image](https://private-user-images.githubusercontent.com/1215090/293612351-b34133a5-9574-49e8-aeca-c1efcb1b7dc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNTUyMjIsIm5iZiI6MTcwNDE1NDkyMiwicGF0aCI6Ii8xMjE1MDkwLzI5MzYxMjM1MS1iMzQxMzNhNS05NTc0LTQ5ZTgtYWVjYS1jMWVmY2IxYjdkYzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDJUMDAyMjAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDdjZjdmYTNlNjgzMGEwNDQyMTc3MGQ4OGMxZDFkZmE4YjFkMzU2MzYwMjU1MjI5Njk0NDJlNTEyZjVkZTkzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sci9x2SI3xvOmpY82FKL4XLMMQjVcbHlUta_Lg5GmiM)
>        Just choose the option like the above image
> 
>     3. You will get the command you need at the end. Then just copy and paste the command on your terminal. Then wait til the installation is completed
> 
>     4. After PyTorch is installed, you can rerun the test script again

Hi, thanks for your fast response.

I run the command and I get this message: 
_Checking ROCM support...
Cannot find rocminfo command information. Unable to determine if AMDGPU drivers with ROCM support were installed._

So that means that I'm stuck with 512mb vram? (My bios don't have the option to modify it ).

**Comment by winstonma** [comment]
`rocminfo` exist only after AMD Graphic Driver is installed. You need to run the following command to install the AMD Driver

```
# Install AMD Driver
TEMP_FOLDER="/tmp"
TEMP_DRIVER_HTML="amd-driver.html"
DISTRO_CODENAME=$(lsb_release --codename --short)

# Find the package URL from AMD website
AMD_DRIVER_URL="https://www.amd.com/en/support/linux-drivers"
URL_RESPONSE=$(wget -U 'Mozilla/5.0' -qO- ${AMD_DRIVER_URL})
AMD_DEB_URL=$(echo $URL_RESPONSE | grep -o 'https://[^ "<]*.deb' | grep $DISTRO_CODENAME | head -1)
FILENAME=$(basename $AMD_DEB_URL)

# Download and install the driver package
wget -P $TEMP_FOLDER $AMD_DEB_URL
sudo dpkg -i $TEMP_FOLDER/$FILENAME
rm $TEMP_FOLDER/$FILENAME

amdgpu-install -y --usecase=rocm
```

You can also find this snippet inside the document that I wrote.

By the way I suggest you running the following command first, I would like to ensure your APU could be supported

```
$ lscpu | grep "Model name"
```

**Comment by edt-xx** [comment]
> It appears ROCm does not take into account dynamic VRAM GTT allocation on APUs (handled by amdkfd?).
> 
> For example on my system:
> 
> ```
> [    3.524465] [drm] amdgpu: 64M of VRAM memory ready
> [    3.524466] [drm] amdgpu: 15916M of GTT memory ready.
> ```
> 
> This means the iGPU could allocate up to 16GB of VRAM, however due to the small dedicated VRAM (64MB) that is _reserved_ for the iGPU, ROCm processes fail to allocate memory.
> 
> This also seems to propagate to OpenCL:

If you use the mesa rusticl opencl driver you will find that it uses the GTT memory as well as the VRAM.

**Comment by winstonma** [comment]
I guess the reason the AMD Graphics Driver doesn't officially support default Ubuntu kernel or your kernel is too old. I think you should run the following step to install the latest default Ubuntu kernel:

```bash
sudo apt update
sudo apt install linux-generic-hwe-22.04
```

Then reboot your system, and wait for the GRUB boot menu comes up. Once in the GRUB menu, select the `Advanced options for Ubuntu` using the arrow keys and press Enter. Then select the default Ubuntu kernel (in my system it is `Ubuntu, with Linux 6.2.0-39-generic`).

Then go back to terminal and check what kernel is running on your system (this is my output to let you know what is the expected output):
```bash
$ awk -F\' '/menuentry / {print $2}' /boot/grub/grub.cfg 
Ubuntu
Ubuntu, with Linux 6.6.8-zabbly+
Ubuntu, with Linux 6.6.8-zabbly+ (recovery mode)
Ubuntu, with Linux 6.2.0-39-generic
Ubuntu, with Linux 6.2.0-39-generic (recovery mode)

Memory test (memtest86+x64.efi, serial console)
Windows Boot Manager (on /dev/nvme0n1p1)
UEFI Firmware Settings
```

The installed kernel is listed between Ubuntu and the extra line (so in my system it is `Linux 6.6.8-zabbly+` and `Linux 6.2.0-39-generic`, ignore the `recovery mode` option). If you see not only `Linux 6.2.0-39-generic` is installed, remove that kernel (please check [this guide](https://linuxconfig.org/how-to-remove-old-kernels-on-ubuntu) for reference.

The default system for installing AMD Graphic Driver should have the output similar to this:
```bash
$ awk -F\' '/menuentry / {print $2}' /boot/grub/grub.cfg 
Ubuntu
Ubuntu, with Linux 6.2.0-39-generic
Ubuntu, with Linux 6.2.0-39-generic (recovery mode)

Memory test (memtest86+x64.efi, serial console)
Windows Boot Manager (on /dev/nvme0n1p1)
UEFI Firmware Settings
```

Only one default Ubuntu kernel.

After you make sure everything is fine. Then reinstall the AMD Graphics Driver

```bash
amdgpu-uninstall
amdgpu-install -y --usecase=rocm
```

**Comment by winstonma** [comment]
> > It appears ROCm does not take into account dynamic VRAM GTT allocation on APUs (handled by amdkfd?).
> > For example on my system:
> > ```
> > [    3.524465] [drm] amdgpu: 64M of VRAM memory ready
> > [    3.524466] [drm] amdgpu: 15916M of GTT memory ready.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This means the iGPU could allocate up to 16GB of VRAM, however due to the small dedicated VRAM (64MB) that is _reserved_ for the iGPU, ROCm processes fail to allocate memory.
> > This also seems to propagate to OpenCL:
> 
> If you use the mesa rusticl opencl driver you will find that it uses the GTT memory as well as the VRAM.

Just wonder if Pytorch use GTT if I use the mesa rusticl opencl driver. If mesa rusticl opencl driver doesn't work with Pytorch don't use GTT by the end then I still have to use this hacky way to fix the video memory.

**Comment by segurac** [comment]
Hi, working on the great initiative of https://github.com/pomoke/torch-apu-helper
I have created this other code that would let us run any PyTorch code and force to use hipHostMalloc without changing a single line of code.

The way it works, it uses LD_PRELOAD to load the functions hipMalloc and hipFree before ROCm runtime and therefore is able to intercept those function calls and then forward them to hipHostMalloc and hipHostFree. hipHostMalloc uses GTT memory and there's no need to change VRAM in the BIOS.

`LD_PRELOAD=./libforcegttalloc.so  HSA_OVERRIDE_GFX_VERSION=9.0.0 python your_pytorch_python_script.py`

Check the code if you think it may be useful.
https://github.com/segurac/force-host-alloction-APU

**Comment by DocMAX** [comment]
Doesn't work on ollama :-(

**Comment by pappacena** [comment]
@segurac great job! I've done some tests, and your memory allocator worked quite well!

To make it easier for future travellers, I've created this [PyPI package](https://pypi.org/project/pytorch-rocm-gtt/) with your code, so anyone can overcome the memory limitation by running this:

```
!pip install pytorch_rocm_gtt
import pytorch_rocm_gtt
pytorch_rocm_gtt.patch()
```

After that, I'm able to allocate way more than the 512MB dedicated to my Radeon 760M iGPU with something like this:
```
>>> torch.rand(1024 * 1024 * 600, dtype=torch.float32, device="cuda") * 10000
tensor([5880.2114, 1243.6473, 3648.3640,  ..., 3309.8118, 6534.8770,
        6562.5479], device='cuda:0')
```

**Comment by DerRehberg** [comment]
Can someone give me a command line tutorial to use more than 2GB with Stable Diffusion? I managed to run it and it almost generated the picture. But I only got 2GB of VRAM and it doesn't have enough video memory to finish the picture. I'm alreadys thinking about download windows to allocate more if possible

**Comment by winstonma** [comment]
@DerRehberg Which CPU are you running? Could you print the result of the following command? This is the output from my system:

```
$glxinfo -B
...
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 512 MB
    Total available memory: 8126 MB
    Currently available dedicated video memory: 57 MB
...
```

**Comment by DerRehberg** [comment]
@winstonma 
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 2048 MB
    Total available memory: 12977 MB
    Currently available dedicated video memory: 1531 MB


AMD Ryzen 7 5825U

**Comment by winstonma** [comment]
@DerRehberg Based on your output your system I think you dedicated 2GB of memory to BIOS. Could you check one more thing? I would like to see the GTT memory allowed.

```
$ sudo dmesg | grep amdgpu | grep drm
[    3.929856] [drm] amdgpu kernel modesetting enabled.
[    3.954417] [drm] amdgpu: 512M of VRAM memory ready
[    3.954419] [drm] amdgpu: 7614M of GTT memory ready.
[    4.271639] [drm] Initialized amdgpu 3.57.0 20150101 for 0000:03:00.0 on minor 0
[    4.283886] fbcon: amdgpudrmfb (fb0) is primary device
[    5.698795] amdgpu 0000:03:00.0: [drm] fb0: amdgpudrmfb frame buffer device
```

I think you need to first disable the dedicated memory. Please use feel free to read [Unlocking GPU Memory Allocation on AMD Ryzen™ APU? - Prepare the bootable USB drive](https://medium.com/p/e27b75905056#3fc7) then go to the next section and set it back to AUTO
- Go to Device Manager→AMD CBS→NBIO Common Option→GFX Configuration
- In Integrated Graphics Controller, select `Auto` (I am not sure the correct wording but don't use `Force`)
- In UMA Mode, select `Auto` (I am not sure the correct wording but don't use `UMA_SPECIFIED`)

After set it back to auto then you can use [force-host-alloction-APU](https://github.com/segurac/force-host-alloction-APU) with Pytorch to run stable diffusion on your Graphic Card.

Please leave message if you still have question.

**Comment by DerRehberg** [comment]
Can you give me a detailed instruction how to use force-host-alloction-apu on arch with stable diffusion?

[    5.278774] [drm] amdgpu kernel modesetting enabled.
[    5.392349] [drm] amdgpu: 2048M of VRAM memory ready
[    5.392352] [drm] amdgpu: 10929M of GTT memory ready.
[    6.617177] [drm] Initialized amdgpu 3.57.0 20150101 for 0000:03:00.0 on minor 1
[    6.624152] fbcon: amdgpudrmfb (fb0) is primary device
[    6.667498] amdgpu 0000:03:00.0: [drm] fb0: amdgpudrmfb frame buffer device
[ 1557.803120]  amdgpu_drm_ioctl+0x4e/0x90 [amdgpu]
[ 1557.803120]  amdgpu_drm_ioctl+0x4e/0x90 [amdgpu]

**Comment by winstonma** [comment]
@DerRehberg I think you should have 10GB of memory. But you better 

```bash
# Of coz you need to install PyTorch ROCm version to replace your PyTorch CPU version
$ pip uninstall torch torchvision torchaudio
$ pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.7

# Go to your Stable Diffusion folder

# Compile the library
$ git clone https://github.com/segurac/force-host-alloction-APU.git
$ CUDA_PATH=/usr/ HIP_PLATFORM="amd" hipcc force-host-alloction-APU/forcegttalloc.c -o force-host-alloction-APU/libforcegttalloc.so  -shared -fPIC
$ sudo mv force-host-alloction-APU/libforcegttalloc.so /usr/local/lib
$ rm -rf force-host-alloction-APU

$ LD_PRELOAD=libforcegttalloc.so HSA_OVERRIDE_GFX_VERSION=9.0.0 python launch.py
```

**Comment by DerRehberg** [comment]
@winstonma Pip uninstall says I should use the AUR xd

**Comment by DerRehberg** [comment]
@winstonma Why can't it load libforcegttalloc?

**Comment by pappacena** [comment]
@DerRehberg I also have this exact random "GPU Hang" while testing mistral-7b (including my KDE crashing). One thing that helped *a little bit* was increasing the dedicated memory in BIOS (I can only increase to 2GB, and mistral-7b uses way more than that, but libforcegttalloc allows the extra allocation).

I still have this crash some times, but it appears to be less frequent this way.

**Comment by winstonma** [comment]
@DerRehberg @pappacena Do you think replacing the `/lib/firmware` with latest version would help? ([instruction](https://tutorialforlinux.com/2022/12/21/how-to-update-linux-firmware-on-ubuntu-22-04-guide/2/)). At least my laptop get smooth VP9 decode and sleep of death problem is gone after updating the firmware folder. So I personally think it's worth to try.

**Comment by DerRehberg** [comment]
@winstonma I think my firmware is actually up to date
@pappacena My Stable Diffusion crashes but Ollama works with it

**Comment by winstonma** [comment]
The system [firmware](https://wiki.ubuntu.com/Kernel/Firmware) (including wifi/bluetooth/chipset) is different from the firmware of the motherboard. I would recommend you to take a look. It fixes several problems of my laptop after me not using the [linux-firmware](https://packages.ubuntu.com/jammy-updates/linux-firmware) (which is 2 years old on Ubuntu Jammy) comes from the system and use the git version. I think there are some advantage using the latest linux-firmware and kernel but still it is up to you.

**Comment by DerRehberg** [comment]
I use Arch @winstonma

**Comment by pomoke** [comment]
Use ROCm 5.7 for Vega-based iGPUs. Versions from ROCm 6.0 will break things as they dropped support for GCN without explicit error message.

**Comment by DerRehberg** [comment]
Well ROCM works with any Software I can imagine on my APU with Version 6. But Stable Diffusion just plainly nicely gives me an out of memory error

**Comment by winstonma** [comment]
@DerRehberg It is just a distracting story.

I just installed Ubuntu 24.04 and find out I don't need to install AMD ROCm Driver in order to get everything working.

I also checked your system and it seems to me that you also don't need to install AMD ROCm Driver. Just need to install [hip-runtime-amd](https://archlinux.org/packages/extra/x86_64/hip-runtime-amd/files/), compile force-host-allocation and everything should be working without the need of ROCm Driver.

**Comment by DerRehberg** [comment]
@winstonma Well I got that package installed. Still crashes on me

**Comment by DerRehberg** [comment]
@winstonma Google Translate Page doesn't support Japanese. And honestly. I just generate with my fucking cpu because I don't care anymore. If I use forcegtt my whole system crashes with stable diffusion

**Comment by DerRehberg** [comment]
@winstonma I found an english article, I would love to try it but at the checking script if rocm works I get an libtorch_cpu error. When Updating torchvision-rocm i also get an error: ImportError: /usr/lib/libtorch_cpu.so: undefined symbol: cblas_gemm_f16f16f32

Idk it anything if fucked up rn

**Comment by DerRehberg** [comment]
@winstonma Found it out. I only need to downgrade hip-runtime-amd to 5.7.1 and Stable Diffusion works with libforcegtt even tho the rest is at 6

**Comment by winstonma** [comment]
Great to hear. That matched my experience on Ubuntu 24.04 too. No need to install ROCm package and DKMS modules. To me using the new way doesn't provide any performance benefit, just easier installation.

Just wonder if it fix the problem you faced?

**Comment by DerRehberg** [comment]
@winstonma Well I tried downgrading all packages to 5.7.1 and it crashed on me. Updating everything except runtime worked for me, idk why tho

**Comment by winstonma** [comment]
Just saw [https://www.phoronix.com/news/Linux-6.10-AMDKFD-Small-APUs](Linux 6.10 Improves AMD ROCm Compute Support For "Small" Ryzen APUs). Although @segurac patch works flawlessly, I still think the AMD should provide native support. Hopefully using 6.10 would no longer require additional library.

**Comment by Snuupy** [comment]
@winstonma which distro are you using?

> EDIT: Just ran Linux Kernel 6.10-rc1 on my 6800U laptop. As expected I can run stable diffusion without using custom mod like [force-host-alloction-APU](https://github.com/segurac/force-host-alloction-APU) or BIOS modification. AMD eventually fix this problem!

**Comment by winstonma** [comment]
@Snuupy I am using Ubuntu 24.04.

By the way Linux 6.9.9 backported this feature already (You can check commit 8d656c in the [changelog](https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.9.9)). I use Zabbly kernel, you can follow [this instruction](https://ubuntuhandbook.org/index.php/2023/11/linux-kernel-6-6-ubuntu-2204-2004/) to install kernel.

FYI Linux Kernel 6.10 has a [green block while playing video bug](https://gitlab.freedesktop.org/drm/amd/-/issues/3437) on my device so I am still using 6.9 right now.

**Comment by Snuupy** [comment]
@winstonma Thank you for such an informative reply! I'm also running Ubuntu 24.04. I didn't know Zabbly 6.9.9 backported this, thanks! I will try upgrading my kernel 😄

**Comment by winstonma** [comment]
@Snuupy After the kernel support I no longer need to install AMD Driver. I guess you could try uninstall the driver and reinstall the driver if anything doesn't work for you.

As it takes time for the driver team to test on distro, I think it make sense for them to support only on LTS release. But again on Ubuntu 24.04 I didn't install AMD Driver. I only install latest 6.9 kernel and everything just work.

By the way if you want to improve the performance there is a small trick, you can use [RyzenAdj](https://github.com/FlyGoat/RyzenAdj) to adjust the `vrmmax-current`. I use my AMD 6800U as an example. The default value is 90mA but I changed it to 105mA. After that I could get 10-15% increase in stable diffusion. You can try that too.

**Comment by Snuupy** [comment]
@winstonma I just installed the 6.9.10 kernel on my 22.04 LTS machine. In my BIOS for my UM780 (7840HS) I set VRAM to 16GB. In `amdgpu_top` I see: `VRAM: 16384 MiB` and `GTT: 23984 MiB`.

I am testing this model, 27B (29 GiB) https://huggingface.co/bartowski/Big-Tiger-Gemma-27B-v1-GGUF/resolve/main/Big-Tiger-Gemma-27B-v1-Q8_0.gguf in ollama/open-webui

I originally thought it would max out the VRAM and then use GTT (~16GB in VRAM, say the remaining ~13GB in GTT allocation). Instead however, I am seeing this:

```
ollama       | llm_load_tensors: offloading 22 repeating layers to GPU
ollama       | llm_load_tensors: offloaded 22/47 layers to GPU
ollama       | llm_load_tensors:      ROCm0 buffer size = 12624.05 MiB
ollama       | llm_load_tensors:        CPU buffer size = 27591.06 MiB
```

Where the ~12GB is loaded into GTT and VRAM usage is still at 0. Is this expected and what you see as well when you load your models?

**Comment by winstonma** [comment]
@Snuupy I think you can set your VRAM to AUTO (and by default it should be 512MB). If there is no AUTO option then you might need to follow [this article](https://winstonhyypia.medium.com/amd-apu-how-to-modify-the-dedicated-gpu-memory-e27b75905056) to set it to AUTO.

Also the max GTT memory would be half of your system memory. But I think you can change the value (please check [this comment](https://github.com/pytorch/pytorch/issues/107605#issuecomment-2178940189) for more information). I never try that so please contact the commenter if that doesn't work.

Lastly you can check the amount GTT memory by running the command `
sudo dmesg | grep GTT`.

**Comment by Vuepress-hue1** [comment]
https://stackdev.space/questions/when-attempting-to-read-a-line-from-a-file-in-c-and-allocate-memory-dynamically-i-consistently-encounter-poor-results



the answer is found

**Comment by nikelborm** [comment]
@Vuepress-hue1 seems like the actual source (not AI crap): https://stackoverflow.com/questions/34233853/im-trying-to-read-a-line-from-a-file-in-c-and-dynamically-allocate-memory-but-t
