### ISSUE TITLE
rccl test fail with "free(): double free detected in tcache 2" on system with rocm 5.6.1 and MI250

### ISSUE THREAD

**Issue by walkup** [RadeonOpenCompute/ROCm#2448]
RCCL tests were working correctly on our system with older ROCM software, but the same tests fail with "free(): double free detected in tcache 2" after installing ROCM 5.6.1.  The same type of failure occurs with all RCCL tests that we have tried, including all_reduce_perf from the rccl-tests repo.  Our test system has Driver version: 4.18.0-477.21.1.el8_8.x86_64.  This failure prevents multi-gpu AI training jobs on our system with MI250 GPUs.

**Comment by walkup** [comment]
It appears that the issue was with the driver version : after update to "Driver version: 6.1.5" the RCCL tests run correctly.

**Comment by sherryxiao1988** [comment]
Hi @walkup, I am experiencing the same issue. May I ask which driver are you talking about? How did you find out the driver version and how did you update it? Thanks.

**Comment by sherryxiao1988** [comment]
Somehow downgrading to ROCM 5.4.2 worked for me.....
