### ISSUE TITLE
[Issue]: Not available on RX 6750 GRE of stablediffsion

### ISSUE THREAD

**Issue by zhixuan45** [RadeonOpenCompute/ROCm#4546]
### Problem Description

Problems encountered during the installation of stablediffsion
`rocBLAS error: Cannot read /home/zhixuan/miniconda3/envs/sd/lib/python3.10/site-packages/torch/lib/rocblas/library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1032
 List of available TensileLibrary Files : 
"/home/zhixuan/miniconda3/envs/sd/lib/python3.10/site-packages/torch/lib/rocblas/library/TensileLibrary_lazy_gfx942.dat"
"/home/zhixuan/miniconda3/envs/sd/lib/python3.10/site-packages/torch/lib/rocblas/library/TensileLibrary_lazy_gfx906.dat"
"/home/zhixuan/miniconda3/envs/sd/lib/python3.10/site-packages/torch/lib/rocblas/library/TensileLibrary_lazy_gfx1101.dat"
"/home/zhixuan/miniconda3/envs/sd/lib/python3.10/site-packages/torch/lib/rocblas/library/TensileLibrary_lazy_gfx1030.dat"
"/home/zhixuan/miniconda3/envs/sd/lib/python3.10/site-packages/torch/lib/rocblas/library/TensileLibrary_lazy_gfx908.dat"
"/home/zhixuan/miniconda3/envs/sd/lib/python3.10/site-packages/torch/lib/rocblas/library/TensileLibrary_lazy_gfx1100.dat"
"/home/zhixuan/miniconda3/envs/sd/lib/python3.10/site-packages/torch/lib/rocblas/library/TensileLibrary_lazy_gfx900.dat"
"/home/zhixuan/miniconda3/envs/sd/lib/python3.10/site-packages/torch/lib/rocblas/library/TensileLibrary_lazy_gfx90a.dat"
已中止 (核心已转储)
`

### Operating System

Ubuntu 24.04.2 LTS (Noble Numbat)

### CPU

 AMD Ryzen 5 5600G with Radeon Graphics

### GPU

AMD Radeon RX 6750 GRE 10GB

### ROCm Version

ROCm6.2.4

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

ROCk module version 6.10.5 is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.14
Runtime Ext Version:     1.6
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
DMAbuf Support:          YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen 5 5600G with Radeon Graphics
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD Ryzen 5 5600G with Radeon Graphics
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   4464                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            12                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Memory Properties:       
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    28626860(0x1b4cfac) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    28626860(0x1b4cfac) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    28626860(0x1b4cfac) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 4                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    28626860(0x1b4cfac) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx1032                            
  Uuid:                    GPU-XX                             
  Marketing Name:          AMD Radeon RX 6750 GRE 10GB        
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
    L2:                      3072(0xc00) KB                     
    L3:                      98304(0x18000) KB                  
  Chip ID:                 29695(0x73ff)                      
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          128(0x80)                          
  Max Clock Freq. (MHz):   2700                               
  BDFID:                   4608                               
  Internal Node ID:        1                                  
  Compute Unit:            36                                 
  SIMDs per CU:            2                                  
  Shader Engines:          2                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Memory Properties:       
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 120                                
  SDMA engine uCode::      80                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    10469376(0x9fc000) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    10469376(0x9fc000) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1032         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*******                  
Agent 3                  
*******                  
  Name:                    gfx90c                             
  Uuid:                    GPU-XX                             
  Marketing Name:          AMD Radeon Graphics                
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    2                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
    L2:                      1024(0x400) KB                     
  Chip ID:                 5688(0x1638)                       
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1900                               
  BDFID:                   12288                              
  Internal Node ID:        2                                  
  Compute Unit:            7                                  
  SIMDs per CU:            4                                  
  Shader Engines:          1                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Memory Properties:       APU
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 472                                
  SDMA engine uCode::      40                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    14313428(0xda67d4) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    14313428(0xda67d4) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx90c:xnack-   
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***

**Comment by ppanchad-amd** [comment]
Hi @juzi45. Internal ticket has been created to assist with your issue. Thanks!

**Comment by harkgill-amd** [comment]
Hey @juzi45, the error reported is due to a lack of libraries for the `gfx1032` architecture.

The `gfx1032` ISA is identical to `gfx1030` so in this case, you can override to use the existing precompiled libraries with `export HSA_OVERRIDE_GFX_VERSION=10.3.0` which should resolve the errors.

**Comment by juzi45** [comment]
Solved, but hopefully updated in the next version
After all, it's quite uncomfortable to use one-button start

**Comment by zhixuan45** [comment]
I just tried running it, but there was a problem during the raw image phase. I'm afraid the replacement version method still doesn't work.

**Comment by harkgill-amd** [comment]
Could you please share more information on the error you hit during image generation? Any error messages and/or logs would help in investigating the cause.

**Comment by zhixuan45** [comment]
Restarted it a bit and it seems to be no problem anymore, It's a bit long to get stuck in the last 2% though

![Image](https://github.com/user-attachments/assets/286dc514-e3f8-4ba1-9478-3476fa26c4ab)

**Comment by zhixuan45** [comment]
It seems that there is still a mistake, and dozens of pictures have been dropped
I swear it's not an April Fool's joke

![Image](https://github.com/user-attachments/assets/ca21666a-bb87-4140-98aa-5de3145a53e3)

**Comment by harkgill-amd** [comment]
Could you please share the following

1. Output of `pip show torch`
2. Model that you're using with Stable Diffusion
3. Errors/output reported in terminal session from which the web UI was launched (during/after hang)

With this information, I'll give it a run on my end to see if I can reproduce the issue. A couple different Stable Diffusion crashes/hang issues have been resolved by setting environment variables to alter the precision configuration, see https://github.com/ROCm/ROCm/issues/3452#issuecomment-2270259969. Could you please give these a try as well and report back?

**Comment by wintrmut3** [comment]
@harkgill-amd Maybe you can just run these prompts with a big batch size and send back the results here directly? Seems like a test case we aught to add to CI

**Comment by zhixuan45** [comment]
**use model**
 [https://civitai.com/models/971952?modelVersionId=1603515](url)
**show torch output**
`Name: torch
Version: 2.6.0+rocm6.2.4
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3-Clause
Location: /home/zhixuan/miniconda3/envs/sd/lib/python3.10/site-packages
Requires: filelock, fsspec, jinja2, networkx, pytorch-triton-rocm, sympy, typing-extensions
Required-by: accelerate, clean-fid, clip, facexlib, kornia, open-clip-torch, pytorch-lightning, spandrel, spandrel_extra_arches, timm, tomesd, torchaudio, torchdiffeq, torchmetrics, torchsde, torchvision
`
**Web UI CL output**
https://paste.ubuntu.com/p/Y73RrfQ5J2/

**Comment by harkgill-amd** [comment]
@juzi45, I was able to reproduce the grey output screen with images being dropped on a 7900 XT. This however, only occurred when I tried to use the LoRA you linked as a model/Stable Diffusion checkpoint rather than a supplementary weight applied to the prompt. See this [post ](https://www.reddit.com/r/StableDiffusion/comments/16y4q3y/can_someone_help_me_fix_why_my_stable_diffusion/)for more information on a similar issue. 

Could you try to generate an image with a basic model and without the use of LoRAs? This worked correctly on my end and will help narrow down whether there's any actual issues on the ROCm end or if it's unique to your Stable Diffusion workflow.

**Comment by zhixuan45** [comment]
It looks like everything is fine with the default model, but the effect may be a little off

![Image](https://github.com/user-attachments/assets/a93f092e-7f8c-46d6-b37c-9bd68b6aea39)

In addition, in Hires, the last part cannot be output when the fix component is enabled, which is reflected in the stuck at 98%

![Image](https://github.com/user-attachments/assets/9701f51e-de2d-4961-ba39-f246f29837cc)

**Comment by harkgill-amd** [comment]
Glad to hear the image generation is working on your end!

I'm not able to reproduce any issues with Hires. Image generation was initially getting stuck at 98% for ~5-10s but would always complete. Give this same workflow a try with the latest [ROCm 6.4 PyTorch wheels](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/3rd-party/pytorch-install.html#using-a-wheels-package). If this doesn't work, I'd recommend opening an issue/discussion over on the [Stable Diffusion project](https://github.com/AUTOMATIC1111/stable-diffusion-webui). I've already seen a couple posts referencing [similar issues](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/8397) and the community over there will be able to point you to different settings and or workarounds to resolve this. Will close out this issue for now, but feel free to leave a comment if you have any questions.
