### ISSUE TITLE
[Issue]: The rocblas of 6.4.0 release doesn't ship TensileLibrary files for gfx906

### ISSUE THREAD

**Issue by ye-luo** [RadeonOpenCompute/ROCm#4625]
### Problem Description

Getting an error
```
rocBLAS error: Cannot read /opt/rocm-6.4.0/lib/rocblas/library/TensileLibrary.dat: No such file or directory for GPU arch : gfx906
 List of available TensileLibrary Files : 
"/opt/rocm-6.4.0/lib/rocblas/library/TensileLibrary_lazy_gfx1101.dat"
"/opt/rocm-6.4.0/lib/rocblas/library/TensileLibrary_lazy_gfx1102.dat"
"/opt/rocm-6.4.0/lib/rocblas/library/TensileLibrary_lazy_gfx1200.dat"
"/opt/rocm-6.4.0/lib/rocblas/library/TensileLibrary_lazy_gfx1030.dat"
"/opt/rocm-6.4.0/lib/rocblas/library/TensileLibrary_lazy_gfx1100.dat"
"/opt/rocm-6.4.0/lib/rocblas/library/TensileLibrary_lazy_gfx1201.dat"
"/opt/rocm-6.4.0/lib/rocblas/library/TensileLibrary_lazy_gfx942.dat"
"/opt/rocm-6.4.0/lib/rocblas/library/TensileLibrary_lazy_gfx90a.dat"
"/opt/rocm-6.4.0/lib/rocblas/library/TensileLibrary_lazy_gfx908.dat"
```
However, Radeon VII gfx906 still listed as deprecated instead of unsupported.
https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html#supported-gpus
rocm 6.3 worked fine.

### Operating System

Ubuntu 24.04

### CPU

AMD CPU

### GPU

Radeon VII

### ROCm Version

6.4.0

### ROCm Component

rocBLAS

**Comment by ppanchad-amd** [comment]
Hi @ye-luo. Internal ticket has been created to look into this issue. Thanks!

**Comment by emerth** [comment]
Can confirm. No gfx906 Tensile files.

```
emerth@5600x:~$ find /opt/rocm-6.4.0/ -type f | grep -i gfx906 | grep -i tensile
emerth@5600x:~$

```
Crickets.

**Comment by zichguan-amd** [comment]
Hi @ye-luo @emerth, thanks for reporting this, we are looking into it. rocblas still supports gfx906, you can build from source to get the TensileLibrary file for gfx906 for now. You can edit [this line](https://github.com/ROCm/rocBLAS/blob/80e5394d6a68901ce48b03da47b33b1e69d58be7/CMakeLists.txt#L115C12-L115C13) to only build for gfx906, this should speed up the build.

**Comment by slavap** [comment]
@zichguan-amd 
and please restore back **deprecated** status for mi50 (it is still supported) in https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html#supported-gpus

**Comment by slavap** [comment]
Just for anyone who won't be able to build from source. I think it is possible to take TensileLibrary_lazy_gfx906.dat from this package: https://archlinux.org/packages/extra/x86_64/rocblas/

Download it and extract.

**Comment by tdavie** [comment]
> Just for anyone who won't be able to build from source. I think it is possible to take TensileLibrary_lazy_gfx906.dat from this package: https://archlinux.org/packages/extra/x86_64/rocblas/
> 
> Download it and extract.

I can confirm that this approach works, at least in inferencing llama cpp on ubuntu 24.04 lts with rocm 6.4. I copied everything that was expected in `/opt/rocm/lib/rocblas/library` and contained the string `gfx906`.

**Comment by 0seba** [comment]
This is a very noob question but I spent all day trying to fix it and couldn't. I cloned rocBLAS to the `release/rocm-rel-6.3.0.2` branch and modified the lines to build for gfx906. I am using the command `./install.sh -idc --no_hipblaslt`, everything goes ok until the very end when it tries to install the package where I get the error
```
dpkg: dependency problems prevent configuration of rocblas:
 rocblas depends on hip-runtime-amd (>= 4.5.0); however:
  Package hip-runtime-amd is not installed.
 rocblas depends on rocm-core; however:
  Package rocm-core is not installed.
```
I installed rocm-6.3.3 with amdgpu-installer and works properly in pytorch and llama.cpp so I'd say it is correctly installed, but I don't know how to overwrite the included rocBLAS with the one I'm build. Both the dependencies seem to be installed
```
dpkg -l | grep hip-runtime-amd
ii  hip-runtime-amd6.3.3                           6.3.42134.60303-74~24.04                 amd64        HIP:Heterogenous-computing Interface for Portability
dpkg -l | grep rocm-core
ii  rocm-core6.3.3
```

**Comment by ye-luo** [comment]
> > Just for anyone who won't be able to build from source. I think it is possible to take TensileLibrary_lazy_gfx906.dat from this package: https://archlinux.org/packages/extra/x86_64/rocblas/
> > Download it and extract.
> 
> I can confirm that this approach works, at least in inferencing llama cpp on ubuntu 24.04 lts with rocm 6.4. I copied everything that was expected in `/opt/rocm/lib/rocblas/library` and contained the string `gfx906`.

Unfortunately it doesn't work on my ubuntu 24.04.
```
rocBLAS error from hip error code: 'hipErrorInvalidDeviceFunction':98
```
I just manually built rocblas from source
```
cmake -DCMAKE_CXX_COMPILER=amdclang++ -DGPU_TARGETS=gfx906 -DCMAKE_INSTALL_PREFIX=/soft/AMD/rocm-gfx906/7.2.0 ..
```
and then use `export LD_LIBRARY_PATH=/soft/AMD/rocm-gfx906/7.2.0/lib:$LD_LIBRARY_PATH`

**Comment by slavap** [comment]
@0seba 
>> I installed rocm-6.3.3 with amdgpu-installer and works properly in pytorch and llama.cpp

Yes, 6.3.3 works and does NOT need any additional manual builds or overrides.

With 6.4.0 you have to fix it with manual build or copy from pre-build package.

**Comment by FantasyMaster85** [comment]
> Just for anyone who won't be able to build from source. I think it is possible to take TensileLibrary_lazy_gfx906.dat from this package: https://archlinux.org/packages/extra/x86_64/rocblas/
> 
> Download it and extract.

Just wanted to chime in and say I can also confirm this works perfectly.  Ubuntu 24.04, AMD Instinct MI60 GPU built llama.cpp and followed these instructions...works perfectly.  I can't believe I spent 2 hours working through a mix of Google and ChatGPT when I just should have started on the Git logged issues.  My fault, lesson learned on that one.  The "old ways" still work! haha.

Thanks for this!!

**Comment by robertofrank-rgb** [comment]
Has anyone managed to get rocm to work with the mi50 in windows?

**Comment by robertofrank-rgb** [comment]
> Just for anyone who won't be able to build from source. I think it is possible to take TensileLibrary_lazy_gfx906.dat from this package: https://archlinux.org/packages/extra/x86_64/rocblas/
> 
> Download it and extract.

Has anyone managed to get rocm to work with the mi50 in windows? so could the mi50 card work with rocm in lmstudio for windows or with koboldccp-rocm for windows??

**Comment by narikm** [comment]
> Just for anyone who won't be able to build from source. I think it is possible to take TensileLibrary_lazy_gfx906.dat from this package: https://archlinux.org/packages/extra/x86_64/rocblas/
> 
> Download it and extract.

What do you mean? Copy all of 'library' or just the file? The file alone failed for me.

**Comment by slavap** [comment]
@narikm 
All files with 906 in filename (156 files in 6.4.0). Pay attention, on archlinux currently 6.4.3 package, which is not compatible with Rocm 6.4.0, so you have to try with Rocm 6.4.3 OR find the url for the previous archlinux package.

<img width="1134" height="1944" alt="Image" src="https://github.com/user-attachments/assets/6713fc30-f412-4f82-8ddd-f2c1035e281b" />

**Comment by MikeLP** [comment]
@slavap  Will this trick work for ROCm7?

**Comment by stanus74** [comment]
### Problem

After applying the gfx906 TensileLibrary fix from #4625, llama.cpp still crashes on MI50 
with ROCm 6.4.3. Debug logs show:
```
Cannot find CO in the bundle /opt/rocm-6.4.3/lib/librocsolver.so.0.4.60403 
for ISA: gfx906:sramecc+:xnack-
```

### Question

Are other MI50/MI60 users hitting the same rocSOLVER gfx906 issue in 6.4.3? 
Is there a fix or should we use ROCm 6.3.3 instead?

### Details
- GPU: MI50 (gfx906)
- Ubuntu 22.04, ROCm 6.4.3
- Works fine with ROCm 6.3.3

**Comment by slavap** [comment]
@stanus74 
Try to get it from here https://archlinux.org/packages/extra/x86_64/rocsolver/
And let us know if it helps.

**Comment by stanus74** [comment]
After applying the ArchLinux rocblas/rocsolver fix for gfx906, the ArchLinux `librocsolver.so.0.4` (622 MB) fails with linker errors on Ubuntu 22.04:

```
undefined reference to `std::ios_base_library_init()@GLIBCXX_3.4.32'
undefined reference to `__isoc23_strtol@GLIBC_2.38'
```

**Root Cause:** ArchLinux rocsolver compiled with newer C++ runtime incompatible with Ubuntu 22.04.

## Catch-22
- ❌ ROCm 6.4.3 rocsolver → Segfault (missing gfx906 CO)
- ❌ ArchLinux rocsolver → Linker Error (incompatible libc/libstdc++)

**Comment by slavap** [comment]
@stanus74 
No wonder, Ubuntu 22 is old, try 24. Or you have to build Rocm by yourself.

**Comment by cpietsch** [comment]
> [@slavap](https://github.com/slavap) Will this trick work for ROCm7?

I managed to compile rocblas for rocm7.1
https://drive.google.com/file/d/1Dmao7DRvS2IMkeUXSWDL5OyAU2TzEEZI/view?usp=sharing
copy them to /opt/rocm-7.1.0/lib/rocblas/library/

**Comment by cpietsch** [comment]
- used: https://github.com/ROCm/rocBLAS/blob/release/rocm-rel-7.1/CMakeLists.txt#L183
- set TENSILE_VERSION to 4.45.0
- apt-get install -y libmsgpack-cxx-dev
- used: https://github.com/ROCm/rocBLAS with branch 'release/rocm-rel-7.1'
- ./install.sh -a gfx906:xnack-

**Comment by Intermountainh8ter** [comment]
For anyone landing here from the gfx906 variant side of this problem: the same gap has a second, nastier form. On cards that report the `sramecc-` ISA variant (Radeon Pro Vega II, Radeon VII, some MI50s with ECC disabled), the libraries don't fail with a clean "no TensileLibrary file" error like the OP's — they **segfault at the first kernel launch**, because the shipped code objects only cover `gfx906:sramecc+` and the HIP runtime crashes instead of erroring on the feature-flag mismatch. Check with:

```
rocminfo | grep -o 'amdgcn-amd-amdhsa--gfx906[^ ]*' | head -1
```

and `AMD_LOG_LEVEL=3` shows `No compatible code objects found for: gfx906:sramecc-:xnack-`. `HSA_OVERRIDE_GFX_VERSION` doesn't help (it's the sramecc flag, not the gfx version). Your own hipcc-compiled kernels work fine, which makes it confusing to diagnose.

Building on what @slavap and others in this thread have been doing by hand — I've packaged the full fix as a repo: parametrized build scripts that clone the `rocm-7.2.3` tags and rebuild **rocBLAS + rocSPARSE + rocALUTION** (in dependency order, with the cmake wiring so each finds the rebuilt libs rather than the broken system ones) for the exact ISA your card reports, into a user-local prefix (no root, system ROCm untouched, `-a "gfx906:xnack-"` same as the recipe above). Plus a prebuilt 7.2.3 release tarball and a validation suite ending in a real rocALUTION GPU CG solve, so you get a definitive pass/fail on your own card:

https://github.com/Intermountainh8ter/rocm-gfx906-sramecc-fix

Tested on 2× Radeon Pro Vega II. MIT (it's AMD's own sources, rebuilt), not affiliated with AMD.

**Comment by cpietsch** [comment]
Hey @Intermountainh8ter thanks for making the scripts in option b. Might be cool to have that as a docker.
