### ISSUE TITLE
[Issue]: ubuntu 24.04 with AMD RYZEN AI MAX+ 395 igpu not detected. Firmware is missing.

### ISSUE THREAD

**Issue by johnxu2013** [RadeonOpenCompute/ROCm#4992]
### Problem Description

$sudo dmesg | grep -i amdgpu

[    3.702135] [drm] amdgpu kernel modesetting enabled.
[    3.705824] amdgpu: Virtual CRAT table created for CPU
[    3.705834] amdgpu: Topology: Add CPU node
[    3.705938] amdgpu 0000:c5:00.0: enabling device (0006 -> 0007)
[    3.708915] amdgpu 0000:c5:00.0: amdgpu: Fatal error during GPU init
[    3.708920] amdgpu 0000:c5:00.0: amdgpu: amdgpu: finishing device.
[    3.708948] amdgpu: probe of 0000:c5:00.0 failed with error -22

it appears that firmware for this gpu is missing. gfx firmwares are not in /lib/firmware/amdgpu.

Can anyone provide firmware?

### Operating System

Ubuntu 24.04.2 LTS (Noble Numbat)

### CPU

AMD RYZEN AI MAX+ 395

### GPU

AMD RYZEN AI MAX+ 395/Radeon 8060S

### ROCm Version

ROCm 6.4.1

**Comment by johnxu2013** [comment]
Model name:             AMD RYZEN AI MAX+ 395 w/ Radeon 8060S
    CPU family:           26

**Comment by xuegao-tzx** [comment]
You can install rocm normally using https://github.com/lamikr/rocm_sdk_builder/

**Comment by johnxu2013** [comment]
This machine works on ollama deepseek-r1 in windows 11 pro using the gpu. And in dual boot ubuntu 24.04, the ollama models processed pretty quick, maybe this is not so critical. I could run models 32b without problem. It may be just ubuntu itself didn't correctly recognize igpu. I would develop using pytorch with cpu code. I also tested using pytorch with directml gpu code on windows 10. pytorch with directml is 5 times slower than the same code running pytorch with cpu.

**Comment by TorgeSchmidt** [comment]
@johnxu2013 Fyi: issue seems to be solved on Ubuntu 25.10
