### ISSUE TITLE
[Issue]: 100% GPU usage for multiple models with pipeline parallel

### ISSUE THREAD

**Issue by DKingAlpha** [RadeonOpenCompute/ROCm#5107]
### Problem Description

`rocm-smi` reports 100% GPU Usage when **multiple** models load with device_map="auto" on a multi-gpu host, idle state.

The 100% GPU issue looks like not a third-party library implementation problem. It happens to:
1. llama.cpp with "-dev ROCm0,ROCm1,...".
2. transformers (sentence_transformers) with device_map="auto"

process CPU usage is around 0%.

I am using gfx906 so I can only test on ROCm 6.3.3.

### Operating System

Arch Linux

### CPU

2 x Intel(R) Xeon(R) E5-2680 v4 (56) @ 3.30 GHz

### GPU

4x MI50 32GB

### ROCm Version

ROCm 6.3.3

### Steps to Reproduce

Code to Reproduce:
```py
import torch
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "Qwen/Qwen3-Embedding-0.6B",
    model_kwargs={
        "device_map": "auto",
        "torch_dtype": torch.float16
    },
    tokenizer_kwargs={"padding_side": "left"},
)
```

Steps to Reproduce:
1. Install torch with ROCm acceleration.
2. pip install sentence_transformers
3. run code above, in two seperate python terminal.

After First model load
```sh
=========================================== ROCm System Management Interface ===========================================
===================================================== Concise Info =====================================================
Device  Node  IDs              Temp    Power     Partitions          SCLK    MCLK    Fan     Perf  PwrCap  VRAM%  GPU%
[3m              (DID,     GUID)  (Edge)  (Socket)  (Mem, Compute, ID)                                                     [0m
========================================================================================================================
0       2     0x66a1,   29631  45.0°C  24.0W     N/A, N/A, 0         925Mhz  350Mhz  14.51%  auto  225.0W  4%     0%
1       3     0x66a1,   33535  47.0°C  19.0W     N/A, N/A, 0         925Mhz  350Mhz  14.51%  auto  225.0W  1%     0%
2       4     0x66a1,   17183  43.0°C  18.0W     N/A, N/A, 0         925Mhz  350Mhz  14.51%  auto  225.0W  1%     0%
3       5     0x66a1,   55003  43.0°C  18.0W     N/A, N/A, 0         925Mhz  350Mhz  14.51%  auto  225.0W  2%     0%
========================================================================================================================
================================================= End of ROCm SMI Log ==================================================
```

After Second model load
```sh
============================================ ROCm System Management Interface ============================================
====================================================== Concise Info ======================================================
Device  Node  IDs              Temp    Power     Partitions          SCLK     MCLK    Fan     Perf  PwrCap  VRAM%  GPU%
[3m              (DID,     GUID)  (Edge)  (Socket)  (Mem, Compute, ID)                                                      [0m
==========================================================================================================================
0       2     0x66a1,   29631  44.0°C  53.0W     N/A, N/A, 0         1725Mhz  350Mhz  15.69%  auto  225.0W  8%     100%
1       3     0x66a1,   33535  48.0°C  45.0W     N/A, N/A, 0         1725Mhz  350Mhz  16.08%  auto  225.0W  3%     100%
2       4     0x66a1,   17183  44.0°C  48.0W     N/A, N/A, 0         1725Mhz  350Mhz  14.51%  auto  225.0W  3%     100%
3       5     0x66a1,   55003  44.0°C  44.0W     N/A, N/A, 0         1725Mhz  350Mhz  14.51%  auto  225.0W  4%     100%
==========================================================================================================================
================================================== End of ROCm SMI Log ===================================================
```

After Second model **unload**
```sh
=========================================== ROCm System Management Interface ===========================================
===================================================== Concise Info =====================================================
Device  Node  IDs              Temp    Power     Partitions          SCLK    MCLK    Fan     Perf  PwrCap  VRAM%  GPU%
[3m              (DID,     GUID)  (Edge)  (Socket)  (Mem, Compute, ID)                                                     [0m
========================================================================================================================
0       2     0x66a1,   29631  44.0°C  24.0W     N/A, N/A, 0         925Mhz  350Mhz  14.51%  auto  225.0W  4%     0%
1       3     0x66a1,   33535  48.0°C  18.0W     N/A, N/A, 0         925Mhz  350Mhz  14.51%  auto  225.0W  1%     0%
2       4     0x66a1,   17183  44.0°C  18.0W     N/A, N/A, 0         925Mhz  350Mhz  14.51%  auto  225.0W  1%     0%
3       5     0x66a1,   55003  44.0°C  18.0W     N/A, N/A, 0         925Mhz  350Mhz  14.51%  auto  225.0W  2%     0%
========================================================================================================================
================================================= End of ROCm SMI Log ==================================================
```

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

```sh
ROCk module is loaded
=====================
HSA System Attributes
=====================
Runtime Version:         1.1
Runtime Ext Version:     1.6
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE
System Endianness:       LITTLE
Mwaitx:                  DISABLED
DMAbuf Support:          YES

......

*******
Agent 3
*******
  Name:                    gfx906
  Uuid:                    GPU-12b008e17337ecd9
  Marketing Name:          AMD Radeon Graphics
  Vendor Name:             AMD
  Feature:                 KERNEL_DISPATCH
  Profile:                 BASE_PROFILE
  Float Round Mode:        NEAR
  Max Queue Number:        128(0x80)
  Queue Min Size:          64(0x40)
  Queue Max Size:          131072(0x20000)
  Queue Type:              MULTI
  Node:                    2
  Device Type:             GPU
  Cache Info:
    L1:                      16(0x10) KB
    L2:                      8192(0x2000) KB
  Chip ID:                 26273(0x66a1)
  ASIC Revision:           1(0x1)
  Cacheline Size:          64(0x40)
  Max Clock Freq. (MHz):   1725
  BDFID:                   1024
  Internal Node ID:        2
  Compute Unit:            60
  SIMDs per CU:            4
  Shader Engines:          4
  Shader Arrs. per Eng.:   1
  WatchPts on Addr. Ranges:4
  Coherent Host Access:    FALSE
  Memory Properties:
  Features:                KERNEL_DISPATCH
  Fast F16 Operation:      TRUE
  Wavefront Size:          64(0x40)
  Workgroup Max Size:      1024(0x400)
  Workgroup Max Size per Dimension:
    x                        1024(0x400)
    y                        1024(0x400)
    z                        1024(0x400)
  Max Waves Per CU:        40(0x28)
  Max Work-item Per CU:    2560(0xa00)
  Grid Max Size:           4294967295(0xffffffff)
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)
    y                        4294967295(0xffffffff)
    z                        4294967295(0xffffffff)
  Max fbarriers/Workgrp:   32
  Packet Processor uCode:: 472
  SDMA engine uCode::      145
  IOMMU Support::          None
  Pool Info:
    Pool 1
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED
      Size:                    33538048(0x1ffc000) KB
      Allocatable:             TRUE
      Alloc Granule:           4KB
      Alloc Recommended Granule:2048KB
      Alloc Alignment:         4KB
      Accessible by all:       FALSE
    Pool 2
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    33538048(0x1ffc000) KB
      Allocatable:             TRUE
      Alloc Granule:           4KB
      Alloc Recommended Granule:2048KB
      Alloc Alignment:         4KB
      Accessible by all:       FALSE
    Pool 3
      Segment:                 GROUP
      Size:                    64(0x40) KB
      Allocatable:             FALSE
      Alloc Granule:           0KB
      Alloc Recommended Granule:0KB
      Alloc Alignment:         0KB
      Accessible by all:       FALSE
  ISA Info:
    ISA 1
      Name:                    amdgcn-amd-amdhsa--gfx906:sramecc+:xnack-
      Machine Models:          HSA_MACHINE_MODEL_LARGE
      Profiles:                HSA_PROFILE_BASE
      Default Rounding Mode:   NEAR
      Default Rounding Mode:   NEAR
      Fast f16:                TRUE
      Workgroup Max Size:      1024(0x400)
      Workgroup Max Size per Dimension:
        x                        1024(0x400)
        y                        1024(0x400)
        z                        1024(0x400)
      Grid Max Size:           4294967295(0xffffffff)
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)
        y                        4294967295(0xffffffff)
        z                        4294967295(0xffffffff)
      FBarrier Max Size:       32
```

### Additional Information

Detailed test with llama.cpp:
1. If multiple MultiGPU models shares any same GPU, `shared GPU` usage goes to 100% instantly on load. `exclusive GPU` usage stays at 0%.
2. SingleGPU model + MultiGPU model works fine.

Test Table:

| First Model -dev | Second Model -dev | 100% GPU Usage (Idle) | 0% GPU Usage (Idle) |
| - | - | - | - |
| 0, 1 | 0, 1 | 0, 1| |
| 0, 1 | 1, 2 | 1|0, 2 |
| 0, 1 | 2, 3 | |0, 1, 2, 3 |
| 0, 1 | 1 | | 0, 1|
| 0, 1 | 2 | | 0, 1, 2|
| 0 | 1 | | 0, 1|

* number in cells: ROCm device index

**Comment by ppanchad-amd** [comment]
Hi @DKingAlpha. Internal ticket has been created to investigate this issue. Thanks!

**Comment by zichguan-amd** [comment]
Hi @DKingAlpha, I'm able to repro the issue with your `sentence_transformers` setup, as well with 2x 7900XTX + ROCm 6.4.3 + torch==2.8.0+rocm6.4. I'm seeing two issues here:

1. GPU util stuck at 100% when loading a second model
2. wtv goes to GPU 1 also gets allocated to GPU 0

Both happens when setting `device_map` to anything except `"cuda:0"`. When allocating solely on GPU 0 I don't see this issue anymore.
However, trying with another method to load models
```
model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen3-Embedding-0.6B",
    torch_dtype=torch.float16,
    device_map="auto"
)
```
Everything behaves as expected. If you can switch to AutoModel + AutoTokenizer it should solve your issue. I haven't tested llama.cpp yet, will have to look into how their model loading differ.

**Comment by DKingAlpha** [comment]
@zichguan-amd Thanks for looking into this. I can confirm AutoModel + AutoTokenizer works as an alternative.

The demo code on the Qwen3-Embedding model page uses `sentence_transformers`, so I went with that. It might be coincidental that they share the same unexpected behavior. Since I dont know much about model loading and GPU tracing, I'll leave that for you to investigate.

**Comment by zichguan-amd** [comment]
I'm not seeing any issues using llama.cpp either. With llama.cpp (5edf1592fdb9131d01321aeef4241c6a34969e27) + 2x 7900XTX+ ROCm 6.3.3, `./llama-cli -hf ggml-org/gemma-3-1b-it-GGUF -dev ROCm0,ROCm1` works as expected.

This seems to be a sentence-transformers issue when loading a model with `device_map`.
When initializing SentenceTransformers, the model gets loaded here https://github.com/UKPLab/sentence-transformers/blob/04ae2e064b0f92d6a80fe6d0cd58827b987e67ee/sentence_transformers/SentenceTransformer.py#L327. This will call into the same transformers backend as with AutoModel, which calls `PreTrainedModel.from_pretrained` This takes `device_map` into account, so it loads everything correctly. But later in the initialization, https://github.com/UKPLab/sentence-transformers/blob/04ae2e064b0f92d6a80fe6d0cd58827b987e67ee/sentence_transformers/SentenceTransformer.py#L367, it does a `self.to(device)` which moves everything to GPU 0. [get_device](https://github.com/UKPLab/sentence-transformers/blob/04ae2e064b0f92d6a80fe6d0cd58827b987e67ee/sentence_transformers/util/environment.py#L14) returns `cuda:0` in this case, you should see `Use pytorch device_name: cuda:0` if you enable logs.

That `self.to(device)` is where the issue is. It somehow keeps the GPU spinning, probably because parts of the model are already allocated on the GPU. If you comment it out, or pause the execution before that line, it behaves as expected. This also explains why stuff in GPU 1 always gets reallocated in GPU 0.

I'm not sure what should be the expected behaviour in this case, but for now let me know if you can get llama.cpp working as expected.

**Comment by DKingAlpha** [comment]
> I'm not seeing any issues using llama.cpp either. With llama.cpp (5edf1592fdb9131d01321aeef4241c6a34969e27) + 2x 7900XTX+ ROCm 6.3.3, `./llama-cli -hf ggml-org/gemma-3-1b-it-GGUF -dev ROCm0,ROCm1` works as expected.
> 
> This seems to be a sentence-transformers issue when loading a model with `device_map`. When initializing SentenceTransformers, the model gets loaded here https://github.com/UKPLab/sentence-transformers/blob/04ae2e064b0f92d6a80fe6d0cd58827b987e67ee/sentence_transformers/SentenceTransformer.py#L327. This will call into the same transformers backend as with AutoModel, which calls `PreTrainedModel.from_pretrained` This takes `device_map` into account, so it loads everything correctly. But later in the initialization, https://github.com/UKPLab/sentence-transformers/blob/04ae2e064b0f92d6a80fe6d0cd58827b987e67ee/sentence_transformers/SentenceTransformer.py#L367, it does a `self.to(device)` which moves everything to GPU 0. [get_device](https://github.com/UKPLab/sentence-transformers/blob/04ae2e064b0f92d6a80fe6d0cd58827b987e67ee/sentence_transformers/util/environment.py#L14) returns `cuda:0` in this case, you should see `Use pytorch device_name: cuda:0` if you enable logs.
> 
> That `self.to(device)` is where the issue is. It somehow keeps the GPU spinning, probably because parts of the model are already allocated on the GPU. If you comment it out, or pause the execution before that line, it behaves as expected. This also explains why stuff in GPU 1 always gets reallocated in GPU 0.
> 
> I'm not sure what should be the expected behaviour in this case, but for now let me know if you can get llama.cpp working as expected.

You need `-ngl 999` or `export LLAMA_ARG_N_GPU_LAYERS=999` to get it loading in GPU.

With -ngl999 it's instantly 100%. Without -ngl999 it works as expected.

**Comment by knguyen298** [comment]
@zichguan-amd can we get an update here?

I am also experiencing this issue, 3x Mi50 with RocM 6.4.4 using llama.cpp. 

I load 2 models at start up:

- A small embedding model, using one GPU only
- A small task model, no GPU limitations i.e. using all three GPUs

I then load a large model (gpt-oss-120B), and initially everything seems nominal, GPUs are sitting idle at 15-20W. However the GPUs jump to 100% when inferencing and stay at 100% even after it’s done, drawing 50W each. Unloading the small task model immediately drops GPU power and usage back to normal. Constraining the task model to just one GPU fixes it, as well as using a smaller model that only needs one GPU.

**Comment by zichguan-amd** [comment]
Hi @knguyen298, sorry for the late reply. Things have changed between 6.3.3 and now. I have some different observations with ROCm 7.1 + llama.cpp @ 583cb83416467e8abf9b37349dcf1f6a0083745a. ~~I'm seeing 100% GPU utilization with just one model on a 2x gfx1100 system. With `-ngl 999` GPU utilization goes to 100% as soon as the first MemcpyAsync happens. With `-ngl 0` everything looks fine after model loads, but after an inference the GPU 0's utilization would get stuck at 100%. Nothing shows up when profiling the workload, there doesn't seem to be any GPU activity that's actually happening (no queues and dispatchs).~~

I've escalated the issue, and I'll make sure that it gets the attention from the right component team. Currently I can't narrow the issue down yet, `hipMemcpyAsync` alone doesn't trigger this behaviour. Please let me know if we are seeing the same issue and if you can find any smaller workloads/easier reproducer.

Edit: I was on an old firmware and observing a different issue. Latest firmware resolves it, and I see the same behaviour as OP and other people's comments.

**Comment by rsarwar87** [comment]
Hi. 

i am having similar issues on gfx1151. whenever i load more than 2 models, usage goes to 100 pc. these are the models i was loading. ressespective of which model, 3 models are loaded usage goes to 100pc. 

gpt-oss 20/120 are on 6.4.4.
glm on rocm 7.11
gemma on rocm 7.10

<img width="1184" height="265" alt="Image" src="https://github.com/user-attachments/assets/38c1cb8d-551d-450e-81d9-00e536b6c2da" />

**Comment by zichguan-amd** [comment]
For now, you can work around it by build llama.cpp with `-DGGML_CUDA_NO_PEER_COPY=ON`. This disables peer to peer copy between GPUs and instead route them through CPU. It will be slower, but you can still offload the models across multiple GPUs.

**Comment by rsarwar87** [comment]
Hi. I am on single gpu. Strix halo.

> For now, you can work around it by build llama.cpp with `-DGGML_CUDA_NO_PEER_COPY=ON`. This disables peer to peer copy between GPUs and instead route them through CPU. It will be slower, but you can still offload the models across multiple GPUs.

**Comment by zichguan-amd** [comment]
Hi @rsarwar87, that sounds like a different issue, might be related but I'm not seeing anything like this on gfx906 and gfx1100. Can you share your system config and provide repro steps?

**Comment by zichguan-amd** [comment]
Hi @rsarwar87, I can confirm that this also happens on a single GPU system, with enough (3+) instances of llama.cpp running. It appears to be the same issue as https://github.com/ROCm/ROCm/issues/2625, using `GPU_MAX_HW_QUEUES=1` will allow you to launch more instances of llama.cpp without running into the problem. But eventually when you have enough processes running you will hit this issue. Kernel team is actively investigating this issue, I'll report back once we have more updates.

**Comment by rsarwar87** [comment]
Hi @zichguan-amd  thanks for confirming the issue. 
also noticed that the same issue occurs when I load models using ROCm and a third model using radv. does it still fall within expectation? Could it be an amdgpu firmware/kernel module, maybe? i only tested kernel 6.17, but considering it was first reported months ago (years if you consider #2625), i expect earlier kernels will have the same issue

I will try the GPU_MAX_HW_QUEUES flag and report back.

Regarding the build process, my Docker images are derived heavily from llama-lemonade, but I do apply rocWMMA patch. unclear if that could be related.

**Comment by zichguan-amd** [comment]
My assumption was that this might be a hardware scheduling issue, which would be related to firmware or kernel driver. So Vulkan could also be affected.

**Comment by zichguan-amd** [comment]
Some updates for gfx12, there is a MES fw fix available from amdgpu driver `31.20.0` with MES `0x8b` or later. Fix for gfx11 and gfx906 is still under development since these archs do not share the same fw logic as gfx12.

**Comment by soulafein83** [comment]
> Some updates for gfx12, there is a MES fw fix available from amdgpu driver `31.20.0` with MES `0x8b` or later. Fix for gfx11 and gfx906 is still under development since these archs do not share the same fw logic as gfx12.

Thanks for the update! You mentioned that fixes for gfx11 and gfx906 are currently under development, but what about the gfx10 architecture?

My RX 6600 (gfx1032) suffers from the exact same 100% idle GPU usage bug when loading multiple models simultaneously. Are there any plans or considerations to develop or backport this MES firmware fix for gfx10 as well?

**Comment by zichguan-amd** [comment]
Hi @soulafein83, gfx10 will likely be similar to gfx11, the issue cannot be simply addressed in MES, changes to CP logics are also needed. I've noted your request down for gfx10. Will report back once I have more information.

**Comment by lhl** [comment]
I'm seeing a related hardware-queue/MES failure on a single-gfx1151 system. I don't have root cause analysis to compare to the multi-model report, but the low-power 100%-utilization state and the `GPU_MAX_HW_QUEUES=1` A/B are a close match, so this may be useful gfx11 evidence:

### System

- Framework Desktop / Ryzen AI MAX+ 395
- Radeon 8060S Graphics, `gfx1151`, single GPU
- Linux `7.1.3-2-cachyos`
- TheRock HIP `7.15.0-0000000`, AMD clang 23 (`aa451e1f...`)
- MES firmware `0x00000088`; MES KIQ firmware `0x0000006f`
- BIOS 03.04 (2025-11-19)
- One resident process/model, approximately 25.493 GiB tracked device allocations

The workload is [hipEngine](https://github.com/shisa-ai/hipEngine)'s torch-free GGUF runtime, clean local commit `4d0aa281f3e1aa0d251562abfb70e200cc28129a`, loading Qwen3.6-35B-A3B UD-Q4_K_M with BF16 KV. The test is a 131072-token bulk prefill followed by 128 graph-replay decode tokens, using one discarded warmup and three measured repetitions.

### Default hardware-queue result

With `GPU_MAX_HW_QUEUES` unset, a fresh clean-worktree run failed during the **first warmup prefill**. It initially did real work at roughly 122-127 W. About 80 seconds into prefill it abruptly changed to:

- 100% GPU utilization
- 2900 MHz SCLK
- approximately 41-43 W
- no forward progress for the remainder of a bounded 1800-second run
- host process still consuming approximately one CPU core

Four periodic Python traceback dumps, spaced seven minutes apart, all showed the main thread at the same synchronous metadata H2D boundary:

```text
hipengine/core/hip.py:60                         memcpy
hipengine/core/memory.py:52                     copy_host_to_device
hipengine/runtime/qwen35_gguf_runner.py:13311   for_chunk
hipengine/runtime/qwen35_gguf_runner.py:8813    _run_bulk_prefill_and_sample
hipengine/runtime/qwen35_gguf_runner.py:8675    prefill
```

`journalctl -k` for the exact run window contained no amdgpu/KFD fault, ring timeout, VM/page fault, reset, OOM, or thermal warning. Killing the bounded process immediately restored approximately 0% utilization / 17 W without a GPU reset.

Local evidence hashes:

```text
6054859b085c735266bc36e255dde5a56e3f2245ca0458a113e9c16569ad6589  default faulthandler log
e6971e49bf05fbcea86594d06d84bd99806ba32eee14c2c16209d3267c8b1a11  default 10-second telemetry
```

### Single-variable one-queue A/B

I then reran the same clean commit, cached artifacts, model, process protocol, and command with only:

```bash
export GPU_MAX_HW_QUEUES=1
```

That run completed the entire warmup + three measured repetitions normally:

```text
warmup prefill: 499.755238 tok/s
measured prefill: 500.209622, 500.873234, 500.686697 tok/s
measured decode: 28.057010, 28.058320, 28.061789 tok/s
```

All measured final token IDs were exactly `9707`; tracked peak remained 25.492502 GiB. Telemetry stayed in the normal high-power working regime rather than collapsing to approximately 42 W, and the kernel journal again had no faults.

```text
292dcc31d3fa9dd7659793314b2787eb0edb98f211494f80e4edf686343b6a69  one-queue JSON
bbf42b4f8b49e9fde647b64cbe173f69cad75bd8203e70f18c1c6a3bae3b1ebe  one-queue stdout/stderr
5a9f63f481f8834b5499bc726ca46e3e156d10eabea3210fa1cff3ee4585e3ff  one-queue 10-second telemetry
```

The command shape was:

```bash
HIPENGINE_HIP_ARCH=gfx1151 \
python3 scripts/qwen35_readme_sweep.py \
  --engine gguf \
  --model Qwen3.6-35B-A3B-UD-Q4_K_M.gguf \
  --quant gguf_q4_k_m \
  --backend hip_gfx1151 \
  --workloads 131072/128 \
  --warmup-runs 1 --measured-runs 3 \
  --warmup-decode-tokens 1 \
  --force-bulk-prefill --bulk-prefill-attention-mode bulk \
  --use-wmma-prefill --use-gemv-decode --graph-replay-decode \
  --require-cached-build --json result.json
```

The tiny stream/memset reproducer described in #2625 did **not** trigger the symptom on this system under either queue policy, so I do not have a small standalone reproducer and are not asserting an identical mechanism. However, the clean same-command queue-count A/B, gfx11 hardware, low-power 100%-busy state, and repeated host wait in `hipMemcpy` are why this looks related to the gfx11 scheduler/firmware work discussed here.

I'm using `GPU_MAX_HW_QUEUES=1` as a workaround and will report back if it fails or if I find a smaller trigger.

**Comment by lhl** [comment]
Follow-up/correction to my previous gfx1151 report: `GPU_MAX_HW_QUEUES=1` is helpful, but it is **not sufficient to eliminate the failure** on this single-process workload.

I reran the final production publication path from clean detached hipEngine `61a27d7279549843bb3fb0464cb8b120689b9ff1` on the same system/firmware/ROCm stack. The 512/1K/4K/32K/64K components all completed normally. The 128K component recorded `GPU_MAX_HW_QUEUES=1` in provenance and completed its eager warmup at `509.708 prefill tok/s / 28.036 decode tok/s`, but measured pass 1 then remained for more than seven minutes at:

- 100% GPU utilization
- 2900 MHz SCLK
- 44-46 W
- no forward progress / no measured-pass output
- no amdgpu/KFD/ring/VM fault in the kernel journal

Bounded process-group termination again restored idle without a GPU reset.

I ruled out the newest hipEngine launch policy as the trigger: a clean run with device metadata explicitly disabled and bulk-prefill router selection restored from 128 to 512 threads completed warmup at `503.455 tok/s`, then entered the same low-power state in measured pass 1.

I also screened `HSA_ENABLE_SDMA=0` because every captured Python host stack from the original failure waited at the synchronous metadata `hipMemcpy` boundary. With one hardware queue plus SDMA disabled, one warmup + one measured pass completed (`498.492 / 498.688 prefill tok/s`, exact output, unchanged memory). However, a fresh full warmup+3 attempt completed warmup at `499.838 tok/s` and then reproduced the same measured-pass-1 low-power stall. So disabling SDMA is **also not a reliable workaround**.

Local evidence hashes:

```text
32d8f3088ba2de40bfd196a0ac2c65272c26d50567ef3a09713d6458fe5729ea  current one-queue failed log
b087ee501ec4a38af70ec5e2841a35e32b72fce34eb75bfb9e7ef9ff4442b058  one-queue + launch-policy rollback failed log
047489b74b8566edbf08d7068f7a63ff3f66c798fd74b7ea1ef92748c716ae42  one-queue + HSA_ENABLE_SDMA=0 successful 1+1 log
16618b328edd304cd913049b87a4fa0fb6298423999106f3c4214a6ca16c51aa  successful 1+1 JSON
90840717db62c991f2d61848c477f1d2f8d135e9af6e9ae992bbaeca8a27d218  one-queue + HSA_ENABLE_SDMA=0 failed full-gate log
```

This is consistent with the issue comment above that one hardware queue raises the failure threshold but can eventually hit the same scheduler problem. I am retaining `GPU_MAX_HW_QUEUES=1` as a risk-reducing gfx1151 default because it fixed the original matched A/B and is non-regressive at short context, but I am no longer describing it as lifecycle-safe for repeated 128K production. Current 128K publication is blocked pending the gfx11 firmware/kernel fix (or a production-quality workaround stronger than the module's documented debug-only non-HWS policy).

**Comment by zichguan-amd** [comment]
Hi @lhl, thanks for the additional information. The issue described does look like the same issue. I suspect hipEngine is launching multiple threads/streams that might oversubscribe the CP. Do you have `mes_set_hw_res_pkt.oversubscription_timer = 0;` set by any chance? Usually, oversubscription is not an issue that stales the progress, it just prevents the GPU from going idle because it needs to constantly poll for those unmapped queues. Stalling seems like either it's really heavily oversubscribed, or the oversubscription timer is disabled.

**Comment by lhl** [comment]
Follow-up to my earlier gfx1151 comments: I have filed the distinct single-process forward-progress failure as **#6437** so it can be tracked separately from this issue's multi-model/idle-utilization symptom.

New evidence since the previous correction:

- The first 128K prefill after rebooting with `amdgpu.mes_log_enable=1 amdgpu.gpu_recovery=1 amdgpu.send_sigterm=1` reproduced at submitted/completed same-stream cursor **389/339**.
- All 36 final telemetry samples remained at **100% / 2.9 GHz / 41–49 W** with fixed residency.
- One established-stall gfx11 HQD dump shows the primary 1 MiB AQL queue **active and non-empty** at `rptr=0x32250`, `wptr=0x32450` (**32 unread AQL packets** after the KFD four-bit AQL pointer shift), with `CP_HQD_ERROR=0` and `CP_HQD_DEQUEUE_REQUEST=0`.
- The exposed MES event-log bytes are identical in healthy-active, first-stall, and +30-second snapshots, then change during monitor-requested SIGTERM teardown.
- No autonomous SIGTERM, user-queue timeout, recovery, or reset fires. Killing only the process clears the state immediately without a GPU reset.
- HIP 7.13 and 7.15 both reproduce; SDMA-off, metadata reuse/rollback, removed scalar readbacks, and layer completion markers are not sufficient workarounds.

Evidence boundary: only one stalled HQD sample exists, so this proves unread mapped work at one instant but does **not** establish temporal hardware-pointer immobility or identify a failed packet/kernel. The MES buffer is preserved but not decoded.

Dedicated report and questions for AMD: #6437  
Redacted HQD/MES evidence bundle: https://gist.github.com/lhl/dcdc0eb2e7a8f1bede6088130c383f72

I will keep the forthcoming `sched_policy=2` isolation result on #6437.

**Comment by lhl** [comment]
Neither hipEngine nor our configuration sets `mes_set_hw_res_pkt.oversubscription_timer` to 0.

Verified:

- hipEngine contains no MES packet definition or direct MES/KFD packet submission. It uses the public HIP runtime; `SET_HW_RESOURCES` is built and submitted by the kernel amdgpu driver during MES initialization.
- The exact CachyOS source tag used by the installed `linux-cachyos 7.1.3-2` package sets [`mes_set_hw_res_pkt.oversubscription_timer = 50`](https://github.com/CachyOS/linux/blob/0e558f948dfe28b50d2eb9ddda58900d7de01aac/drivers/gpu/drm/amd/amdgpu/mes_v11_0.c#L717-L723). Package release `-2` rebuilt the same `cachyos-7.1.3-1` source tag for NVIDIA 610.43.03; its only additional LTO-package patch is unrelated `dkms-clang.patch`.
- There is no exposed amdgpu `oversubscription_timer` module parameter on this installation, no matching kernel-command-line/modprobe setting, and we have not patched the kernel. `mes_log_enable=1` only enables the adjacent event-log fields; it does not alter the timer assignment.
- I cannot directly read back the live firmware's accepted copy of this packet field through the available sysfs/debugfs views. Therefore the evidence-bounded statement is that the running kernel image was built from a source path that submits **50**, with no configured override—not that I independently decoded the firmware state. If AMD has a supported packet dump/readback, I can capture it.

I also audited the exact failing hipEngine path for the multiple-thread/stream concern:

- The 128K benchmark calls `session.prefill()` from the main Python thread and queues bulk prefill on HIP's default stream (`stream=0`). It does not use the serving scheduler's worker pools.
- `HIPENGINE_QWEN35_AOTRITON_ISOLATED_PREFILL_STREAM` was not enabled by the capture command, and the `hip_gfx1151` backend capability resolves false. AOTriton therefore receives the same default stream; no lazy secondary prefill stream is created for this capture.
- We did test a separate event-linked AOTriton stream as an explicit candidate earlier. It caused severe intermittent 32K/128K GPU-active stalls, so it was rejected and removed from both backends' defaults before the current same-stream captures. The current failure therefore survives that rollback.
- ROCr has ordinary helper/event threads, but hipEngine is not submitting the failing prefill from multiple application threads.
- The process was launched with `GPU_MAX_HW_QUEUES=1`. KFD still exposed one primary 1 MiB compute queue, one auxiliary 4 KiB compute queue, and one SDMA queue object. In the established stall snapshot both compute HQDs were active: the primary was non-empty with 32 unread AQL packets, while the auxiliary was empty. I do not interpret `GPU_MAX_HW_QUEUES=1` as proof that MES has only one mapped queue.

So a disabled oversubscription timer does not appear to explain this capture. The separate report is #6437. Before changing scheduler policy, I am running one current-boot application rollback to the older fused GDN recurrence; after that, the already-prepared `amdgpu.sched_policy=2` boot will isolate the HWS/MES plane.

**Comment by superm1** [comment]
Could you guys please test this kernel series?

https://patchwork.freedesktop.org/series/171678/

**Comment by lhl** [comment]
> Could you guys please test this kernel series?
> 
> https://patchwork.freedesktop.org/series/171678/

btw I am testing the patch now, doesn't seem to fix my particular mes issues, sadly.

**Comment by superm1** [comment]
In case it's the same issue - what MES F/W version do you have?  You need to have a new enough one to use that patch.
v2 of the patch checks for 0x70 or newer.

https://lore.kernel.org/amd-gfx/20260819201443.282689-1-jinhuieric.huang@amd.com/

If it still doesn't help with 0x70 (or you already have that), you probably have identified a different issue.

**Comment by soulafein83** [comment]
Still reproducible on ROCm 7.14 and ROCm 10.0.
Because of this 100% GPU usage lockup, it's impossible to efficiently run a local LLM alongside a dedicated local embedding model on the same card. This effectively breaks real-world multi-model workflows in applications like AnythingLLM, OpenClaw, or DeepTutor, where low-idle background execution for embeddings is essential.
Is there any progress or a temporary workaround available?

**Comment by superm1** [comment]
The fix is in the kernel driver. The patches for it are landing in mainline kernel 7.4.

**Comment by soulafein83** [comment]
> The fix is in the kernel driver. The patches for it are landing in mainline kernel 7.4.

Got it, thanks for the update! In that case, I'll wait for the kernel 7.4 RC build to become available on CachyOS and test it out then.
