### ISSUE TITLE
[Issue]: hsa_queue_create causes GPU page fault on gfx1151 APU (Ryzen AI Max+ 395, Radeon 8060S)

### ISSUE THREAD

**Issue by tomasthoresen** [RadeonOpenCompute/ROCm#6118]
## Environment
- APU: AMD Ryzen AI Max+ 395 (Strix Halo)
- GPU: Radeon 8060S (gfx1151, RDNA 3.5, Chip ID 0x1586)
- ROCm: 7.2.1 (hsa-rocr 1.18.0.70201-81)
- Driver: amdgpu-dkms 6.19.0 (31.20 series)
- Kernel: 6.17.0-20-generic (Ubuntu 24.04)
- Also tested: amdgpu-dkms 6.16.13 (30.30), kernel 6.17.0-19

## Problem
hsa_queue_create() on the gfx1151 GPU agent causes an immediate
GPU memory access fault and crashes:

  Memory access fault by GPU node-1 (Agent handle: 0x5b19b86e7090) 
  on address 0x767500478000. 
  Reason: Page not present or supervisor privilege.

dmesg shows:
  amdgpu: [gfxhub] page fault (src_id:0 ring:153 vmid:8)
  GCVM_L2_PROTECTION_FAULT_STATUS: 0x00800932
  Faulty UTCL2 client ID: CPF (0x4)
  WALKER_ERROR: 0x1, PERMISSION_FAULTS: 0x3, MAPPING_ERROR: 0x1

This blocks ALL GPU compute: hipStreamCreate, hipMalloc, 
hipModuleLoadData all hang because they go through hsa_queue_create.

## What works
- rocminfo detects the GPU correctly (gfx1151, 40 CUs, KERNEL_DISPATCH)
- rocm-smi shows healthy GPU (32°C, 23W)
- hipInit, hipHostMalloc, hipDeviceSynchronize all work
- hiprtcCompileProgram produces valid code objects
- Display output works fine

## Minimal reproducer (Python)
```python
import ctypes

hsa = ctypes.CDLL('/opt/rocm/lib/libhsa-runtime64.so')

class hsa_agent_t(ctypes.Structure):
    _fields_ = [('handle', ctypes.c_uint64)]

hsa.hsa_init()

AGENT_CB = ctypes.CFUNCTYPE(ctypes.c_int, hsa_agent_t, ctypes.c_void_p)
gpu = hsa_agent_t()

def find_gpu(agent, data):
    dev = ctypes.c_uint32()
    hsa.hsa_agent_get_info(agent, 17, ctypes.byref(dev))
    if dev.value == 1:
        gpu.handle = agent.handle
    return 0

hsa.hsa_iterate_agents(AGENT_CB(find_gpu), None)
queue = ctypes.c_void_p()
# This line crashes with page fault:
hsa.hsa_queue_create(gpu, 1024, 0, None, None, 
    ctypes.c_uint32(0xFFFFFFFF), ctypes.c_uint32(0xFFFFFFFF),
    ctypes.byref(queue))
```

## Impact
Completely blocks GPU compute on Ryzen AI Max+ 395.

## rocminfo GPU output
  Name: gfx1151
  Marketing Name: Radeon 8060S Graphics
  Feature: KERNEL_DISPATCH
  Max Queue Number: 128
  Chip ID: 5510 (0x1586)
  Compute Unit: 40
  Wavefront Size: 32

### Operating System

24.04.4 LTS (Noble Numbat)

### CPU

AMD RYZEN AI MAX+ 395 w/ Radeon™ 8060S × 32

### GPU

Radeon™ 8060S Graphics

### ROCm Version

7.2.1 (hsa-rocr 1.18.0.70201-81)

**Comment by janchk** [comment]
And here we are asking why cuda is winning..

**Comment by amd-nicknick** [comment]
Hi @tomasthoresen, the reproducer you provided works correctly on my system.
For Strix Halo, try to use the OEM kernel instead of DKMS. Follow the instructions here: https://rocm.docs.amd.com/projects/radeon-ryzen/en/latest/docs/install/installryz/native_linux/install-ryzen.html
Specifically, you should remove all DKMS and firmware package installed, and make sure you're using 24.04 OEM kernel.

Could you please help clarify what you're trying to achieve here? I recommend using the hip APIs as that is easier, portable and better documented compared to interfacing with hsa.

**Comment by tomasthoresen** [comment]
@amd-nicknick - Thank you for testing and for the guidance. I can confirm that using the OEM kernel I am able to progress. Thx!

**Comment by amd-nicknick** [comment]
@tomasthoresen, no problem at all. If you encounter any further problem, feel free to create a new issue and we'll take a look. Thanks!

**Comment by KE7** [comment]
Quick data point from another MS-S1 MAX owner: I hit this exact issue on my Ryzen AI Max+ 395. `rocminfo` saw the Radeon 8060S, but any real HIP or PyTorch allocation hit the GFXHUB page fault.

I used Codex to help debug the R9700 eGPU side of my setup. The iGPU part turned out to be much simpler. My machine had AMD's separately installed driver stack, and this is what fixed the 8060S for me:

```sh
sudo apt update
sudo apt install linux-oem-24.04
sudo apt purge amdgpu-dkms amdgpu-dkms-firmware amdgpu-core amdgpu-install
sudo reboot
```

After reboot I checked that I was actually on the OEM kernel and that ROCm saw `gfx1151`:

```sh
uname -r
rocminfo | grep -E 'gfx1151|Radeon 8060S'
```

I also tested a real allocation, not just `rocminfo`. With my ROCm PyTorch environment and no `ROCR_VISIBLE_DEVICES` restriction, the 8060S is device 0 on my machine:

```sh
python - <<'PY'
import torch
torch.cuda.set_device(0)
x = torch.empty(1024, device='cuda:0')
x.fill_(1)
torch.cuda.synchronize()
print(x.sum().item())
PY
```

That fixed the iGPU for me. FreeToken Qwen2.5-1.5B-Instruct then ran at 40.33 tok/s on the 8060S.

My machine also has an R9700 in a Razer Core X V2 on TB5. The OEM change was necessary, but it was not the whole R9700 setup. The R9700 comes up reliably for me when I:

1. Leave the Core connected to the rear 80 Gb/s port before booting.
2. Keep the R9700 (`1002:7551`) isolated at early boot so the 8060S (`1002:1586`) gets the desktop first.
3. After the display manager is running, keep the TB5 router and the R9700 PCI path awake with `power/control=on`.
4. Bind the R9700 to `amdgpu` once through `/sys/bus/pci/drivers/amdgpu/bind`.
5. Keep PCIe runtime PM and ASPM disabled for the eGPU path.

My boot entry also has `pcie_port_pm=off pcie_aspm=off amdgpu.runpm=0`. I use a locally verified R9700 firmware path and a headless virtual display setting too, but those parts are specific to my hardware and should not be copied blindly.

With the above, the R9700 has its full 32 GB VRAM aperture and ran the same FreeToken workload at 43.03 tok/s. Both GPUs gave the same greedy output. I then did a normal reboot and both GPUs came back on the in-tree `amdgpu` driver with no new page faults.

So the OEM-kernel plus AMD-package cleanup fixed the original `gfx1151` compute fault for me. The staged R9700 binding is the extra piece for my TB5 eGPU setup.
