### ISSUE TITLE
Running BatchNorm2D causes miopenStatusUnknownError

### ISSUE THREAD

**Issue by mt88875** [RadeonOpenCompute/ROCm#6150]
To whom it may concern,

When I run the function BatchNorm2D on my RX 9060 XT, it triggers the miopenStatusUnknownError. This is problematic since it makes it impossible for me to train data on many pretrained models. Is there a solution which resolves this issue? Thanks in advance.

**CPU:** i5-12400
**GPU:** RX 9060 XT 16GB
**OS:** Windows 11, version 25H2
**ROCm version:** 7.2.1

**Simple code causing the problem:**
```
import torch.nn as nn
import torch

gpu = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Device used:', torch.cuda.get_device_name())

f = nn.BatchNorm2d(100, device = gpu)
x = torch.randn(size = (20, 100, 35, 45), device = gpu)
output = f(x)
```
**Error message:**
```
MIOpen(HIP): Error [Compile] 'hiprtcCompileProgram(prog.get(), c_options.size(), c_options.data())' MIOpenBatchNormFwdTrainSpatialHIP.cpp: HIPRTC_ERROR_COMPILATION (6)
MIOpen(HIP): Error [BuildHip] HIPRTC status = HIPRTC_ERROR_COMPILATION (6), source file: MIOpenBatchNormFwdTrainSpatialHIP.cpp
MIOpen(HIP): Warning [BuildHip] In file included from C:\Users\matth\AppData\Local\Temp\comgr-2144-9-76ee63\input\MIOpenBatchNormFwdTrainSpatialHIP.cpp:31:
In file included from C:\Users\matth\AppData\Local\Temp\comgr-2144-9-76ee63\include\batchnorm_functions.hpp:30:
In file included from C:\Users\matth\AppData\Local\Temp\comgr-2144-9-76ee63\include\configuration.hpp:36:
C:\Users\matth\AppData\Local\Temp\comgr-2144-9-76ee63\include\miopen_type_traits.hpp:151:10: fatal error: 'type_traits' file not found
  151 | #include <type_traits>
      |          ^~~~~~~~~~~~~
1 error generated when compiling for gfx1200.
MIOpen Error: DESKTOP-FSHC0VD:C:/develop/TheRock/rocm-libraries/projects/miopen/src/hipoc/hipoc_program.cpp:299: Code object build failed. Source: MIOpenBatchNormFwdTrainSpatialHIP.cpp
Traceback (most recent call last):
  File "c:\Users\matth\Documents\Coding Files\Python Files\a.py", line 10, in <module>
    output = f(x)
             ^^^^
  File "C:\Users\matth\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matth\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matth\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\modules\batchnorm.py", line 193, in forward
    return F.batch_norm(
           ^^^^^^^^^^^^^
  File "C:\Users\matth\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\nn\functional.py", line 2813, in batch_norm
    return torch.batch_norm(
           ^^^^^^^^^^^^^^^^^
RuntimeError: miopenStatusUnknownError
```

**Comment by krishkat** [comment]
As I discovered with #6314 this applies also to `nn.Gru` and RDNA 3.5 and it doesn't matter if I use [stable](https://repo.radeon.com/rocm/windows/rocm-rel-7.2.1) or [nightly](https://rocm.nightlies.amd.com/v2/gfx1151/) builds.

**Comment by mt88875** [comment]
> As I discovered with [#6314](https://github.com/ROCm/ROCm/issues/6314) this applies also to `nn.Gru` and RDNA 3.5 and it doesn't matter if I use [stable](https://repo.radeon.com/rocm/windows/rocm-rel-7.2.1) or [nightly](https://rocm.nightlies.amd.com/v2/gfx1151/) builds.

I also run into issues using `nn.LSTM` and `nn.GRU` during back propagation in Windows. A temporary workaround that I found is to use WSL for PyTorch.

**Comment by adityas-amd** [comment]
here compiler fails could be  it cannot find the standard C++ header <type_traits>. So, the likely Windows ROCm packaging, include-path, or toolchain setup issue affecting HIPRTC/MIOpen JIT compilation.
need to verify the exact supported Windows install path, driver version, rocm_sdk_devel installation, PATH/DLL conflicts, and collect `torch.utils.collect_env` plus MIOpen logs.

**Comment by l9565495** [comment]
In my case
just add    torch.backends.cudnn.enabled = False
it will work for therock  torch - 2.11.0+rocm7.13.0a20260416

rocm 7.1.1 also can run test code, not need add torch.backends.cudnn.enabled = False

I using RX9060XT win10 22H2

**Comment by mt88875** [comment]
> here compiler fails could be it cannot find the standard C++ header <type_traits>. So, the likely Windows ROCm packaging, include-path, or toolchain setup issue affecting HIPRTC/MIOpen JIT compilation. need to verify the exact supported Windows install path, driver version, rocm_sdk_devel installation, PATH/DLL conflicts, and collect `torch.utils.collect_env` plus MIOpen logs.

It seems to be a problem relating to Windows since I do not experience this issue in Linux or WSL.

**Comment by mt88875** [comment]
> In my case just add torch.backends.cudnn.enabled = False it will work for therock torch - 2.11.0+rocm7.13.0a20260416
> 
> rocm 7.1.1 also can run test code, not need add torch.backends.cudnn.enabled = False
> 
> I using RX9060XT win10 22H2

This approach works for me as well. However, it increases the training time of the model significantly.

**Comment by l9565495** [comment]
> > In my case just add torch.backends.cudnn.enabled = False it will work for therock torch - 2.11.0+rocm7.13.0a20260416
> > rocm 7.1.1 also can run test code, not need add torch.backends.cudnn.enabled = False
> > I using RX9060XT win10 22H2
> 
> This approach works for me as well. However, it increases the training time of the model significantly.

I try to install Visual Studio Build Tools 2022 & Windows 11 SDK,  the problem was fix.
But runing test code use much time.

**Comment by krishkat** [comment]
The issue still exists in the latest stable ROCm 10:
```
~\Documents ❯ python .\test.py
Device used: AMD Radeon(TM) 8050S Graphics
MIOpen: Error [Compile] 'hiprtcCompileProgram(prog.get(), c_options.size(), c_options.data())' MIOpenBatchNormFwdTrainSpatial.cpp: HIPRTC_ERROR_COMPILATION (6)
MIOpen: Error [BuildHip] HIPRTC status = HIPRTC_ERROR_COMPILATION (6), source file: MIOpenBatchNormFwdTrainSpatial.cpp
MIOpen: Warning [BuildHip] In file included from C:\Users\krishkat\AppData\Local\Temp\comgr-9004-512-cc9f7f\input\MIOpenBatchNormFwdTrainSpatial.cpp:8:
In file included from C:\Users\krishkat\AppData\Local\Temp\comgr-9004-512-cc9f7f\include\batchnorm_functions.hpp:30:
In file included from C:\Users\krishkat\AppData\Local\Temp\comgr-9004-512-cc9f7f\include\configuration.hpp:34:
In file included from C:\Users\krishkat\AppData\Local\Temp\comgr-9004-512-cc9f7f\include\vector_types.hpp:8:
C:\Users\krishkat\AppData\Local\Temp\comgr-9004-512-cc9f7f\include\miopen_type_traits.hpp:151:10: fatal error: 'type_traits' file not found
  151 | #include <type_traits>
      |          ^~~~~~~~~~~~~
1 error generated when compiling for gfx1151.
MIOpen Error: DESKTOP-FFH0L11:C:/home/runner/_work/rockrel/rockrel/rocm-libraries/projects/miopen/src/hipoc/hipoc_program.cpp:204: Code object build failed. Source: MIOpenBatchNormFwdTrainSpatial.cpp
Traceback (most recent call last):
  File "C:\Users\krishkat\Documents\test.py", line 9, in <module>
    output = f(x)
  File "C:\Users\krishkat\AppData\Local\Programs\Python\Python314\Lib\site-packages\torch\nn\modules\module.py", line 1778, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\krishkat\AppData\Local\Programs\Python\Python314\Lib\site-packages\torch\nn\modules\module.py", line 1789, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\krishkat\AppData\Local\Programs\Python\Python314\Lib\site-packages\torch\nn\modules\batchnorm.py", line 210, in forward
    return F.batch_norm(
           ~~~~~~~~~~~~^
        input,
        ^^^^^^
    ...<11 lines>...
        self.eps,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\krishkat\AppData\Local\Programs\Python\Python314\Lib\site-packages\torch\nn\functional.py", line 2898, in batch_norm
    return torch.batch_norm(
           ~~~~~~~~~~~~~~~~^
        input,
        ^^^^^^
    ...<7 lines>...
        torch.backends.cudnn.enabled,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
RuntimeError: miopenStatusUnknownError
~\Documents ❯ python -m torch.utils.collect_env
<frozen runpy>:130: RuntimeWarning: 'torch.utils.collect_env' found in sys.modules after import of package 'torch.utils', but prior to execution of 'torch.utils.collect_env'; this may result in unpredictable behaviour
Collecting environment information...
PyTorch version: 2.13.0+rocm10.0.0
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 7.15.26333

OS: Microsoft Windows 11 Pro (10.0.26200 64-Bit)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.14.7 (tags/v3.14.7:823f032, Aug  5 2026, 10:51:32) [MSC v.1944 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-11-10.0.26200-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to:
GPU models and configuration: AMD Radeon(TM) 8050S Graphics (gfx1151)
Nvidia driver version: Could not collect
cuDNN version: Could not collect
Is XPU available: False
HIP runtime version: 7.15.26333
MIOpen runtime version: 3.6.0
Is XNNPACK available: False
Caching allocator config: N/A

CPU:
Name: AMD RYZEN AI MAX 385 w/ Radeon 8050S
Manufacturer: AuthenticAMD
Family: 107
Architecture: 9
ProcessorType: 3
DeviceID: CPU0
CurrentClockSpeed: 3600
MaxClockSpeed: 3600
L2CacheSize: 8192
L2CacheSpeed: None
Revision: 28672

Versions of relevant libraries:
[pip3] amd-torch-device-gfx1151==2.13.0+rocm10.0.0
[pip3] amd-torch-device-gfx115x==2.13.0+rocm10.0.0
[pip3] amd-torchvision-device-gfx1151==0.28.0+rocm10.0.0
[pip3] numpy==2.5.2
[pip3] torch==2.13.0+rocm10.0.0
[pip3] torchaudio==2.11.0.2+rocm10.0.0
[pip3] torchvision==0.28.0+rocm10.0.0
[conda] Could not collect
```
